
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  UserCoin: 'UserCoin',
  Strategy: 'Strategy',
  Trade: 'Trade',
  Wallet: 'Wallet',
  Backtest: 'Backtest',
  Coin: 'Coin',
  Balance: 'Balance',
  PortfolioHistory: 'PortfolioHistory',
  WalletTrade: 'WalletTrade',
  Snapshot: 'Snapshot',
  Notification: 'Notification'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  emailVerified: 'emailVerified',
  username: 'username',
  image: 'image',
  password: 'password',
  email: 'email'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires',
  type: 'type',
  attempts: 'attempts',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VerificationTokenScalarFieldEnum = (typeof VerificationTokenScalarFieldEnum)[keyof typeof VerificationTokenScalarFieldEnum]


export const UserCoinScalarFieldEnum = {
  userId: 'userId',
  coinId: 'coinId',
  isOptimistic: 'isOptimistic'
} as const

export type UserCoinScalarFieldEnum = (typeof UserCoinScalarFieldEnum)[keyof typeof UserCoinScalarFieldEnum]


export const StrategyScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  type: 'type',
  settings: 'settings',
  parameters: 'parameters',
  coinId: 'coinId',
  timeframe: 'timeframe',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StrategyScalarFieldEnum = (typeof StrategyScalarFieldEnum)[keyof typeof StrategyScalarFieldEnum]


export const TradeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  strategyId: 'strategyId',
  coinId: 'coinId',
  mode: 'mode',
  entryPrice: 'entryPrice',
  exitPrice: 'exitPrice',
  amount: 'amount',
  profitLoss: 'profitLoss',
  status: 'status',
  executedAt: 'executedAt',
  closedAt: 'closedAt'
} as const

export type TradeScalarFieldEnum = (typeof TradeScalarFieldEnum)[keyof typeof TradeScalarFieldEnum]


export const WalletScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  provider: 'provider',
  address: 'address',
  isActive: 'isActive',
  createdAt: 'createdAt'
} as const

export type WalletScalarFieldEnum = (typeof WalletScalarFieldEnum)[keyof typeof WalletScalarFieldEnum]


export const BacktestScalarFieldEnum = {
  id: 'id',
  strategyId: 'strategyId',
  userId: 'userId',
  timeframe: 'timeframe',
  fromDate: 'fromDate',
  toDate: 'toDate',
  pnlPercent: 'pnlPercent',
  numTrades: 'numTrades',
  winRate: 'winRate',
  maxDrawdown: 'maxDrawdown'
} as const

export type BacktestScalarFieldEnum = (typeof BacktestScalarFieldEnum)[keyof typeof BacktestScalarFieldEnum]


export const CoinScalarFieldEnum = {
  id: 'id',
  name: 'name',
  symbol: 'symbol',
  image: 'image'
} as const

export type CoinScalarFieldEnum = (typeof CoinScalarFieldEnum)[keyof typeof CoinScalarFieldEnum]


export const BalanceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  coinId: 'coinId',
  amount: 'amount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BalanceScalarFieldEnum = (typeof BalanceScalarFieldEnum)[keyof typeof BalanceScalarFieldEnum]


export const PortfolioHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  coinId: 'coinId',
  date: 'date',
  usdValue: 'usdValue'
} as const

export type PortfolioHistoryScalarFieldEnum = (typeof PortfolioHistoryScalarFieldEnum)[keyof typeof PortfolioHistoryScalarFieldEnum]


export const WalletTradeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fromCoinId: 'fromCoinId',
  toCoinId: 'toCoinId',
  fromAmount: 'fromAmount',
  toAmount: 'toAmount',
  fromPrice: 'fromPrice',
  toPrice: 'toPrice',
  status: 'status',
  executedAt: 'executedAt'
} as const

export type WalletTradeScalarFieldEnum = (typeof WalletTradeScalarFieldEnum)[keyof typeof WalletTradeScalarFieldEnum]


export const SnapshotScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  date: 'date',
  portfolioValue: 'portfolioValue',
  perCoinValue: 'perCoinValue',
  realizedPL: 'realizedPL',
  unrealizedPL: 'unrealizedPL'
} as const

export type SnapshotScalarFieldEnum = (typeof SnapshotScalarFieldEnum)[keyof typeof SnapshotScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  message: 'message',
  link: 'link',
  read: 'read',
  createdAt: 'createdAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

