
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model UserCoin
 * 
 */
export type UserCoin = Prisma.UserCoinModel
/**
 * Model Strategy
 * 
 */
export type Strategy = Prisma.StrategyModel
/**
 * Model Trade
 * 
 */
export type Trade = Prisma.TradeModel
/**
 * Model Wallet
 * 
 */
export type Wallet = Prisma.WalletModel
/**
 * Model Backtest
 * 
 */
export type Backtest = Prisma.BacktestModel
/**
 * Model Coin
 * 
 */
export type Coin = Prisma.CoinModel
/**
 * Model Balance
 * 
 */
export type Balance = Prisma.BalanceModel
/**
 * Model PortfolioHistory
 * 
 */
export type PortfolioHistory = Prisma.PortfolioHistoryModel
/**
 * Model WalletTrade
 * 
 */
export type WalletTrade = Prisma.WalletTradeModel
/**
 * Model Snapshot
 * 
 */
export type Snapshot = Prisma.SnapshotModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
