
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const StrategyType = {
  DCAa: 'DCAa',
  GRID: 'GRID',
  INDICATOR: 'INDICATOR',
  MANUAL: 'MANUAL'
} as const

export type StrategyType = (typeof StrategyType)[keyof typeof StrategyType]


export const TradeMode = {
  TEST: 'TEST',
  REAL: 'REAL'
} as const

export type TradeMode = (typeof TradeMode)[keyof typeof TradeMode]


export const TradeStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
} as const

export type TradeStatus = (typeof TradeStatus)[keyof typeof TradeStatus]


export const VerificationTokenType = {
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  PASSWORD_RESET: 'PASSWORD_RESET',
  EMAIL_OTP: 'EMAIL_OTP'
} as const

export type VerificationTokenType = (typeof VerificationTokenType)[keyof typeof VerificationTokenType]


export const WalletTradeStatus = {
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type WalletTradeStatus = (typeof WalletTradeStatus)[keyof typeof WalletTradeStatus]
