
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Backtest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Backtest
 * 
 */
export type BacktestModel = runtime.Types.Result.DefaultSelection<Prisma.$BacktestPayload>

export type AggregateBacktest = {
  _count: BacktestCountAggregateOutputType | null
  _avg: BacktestAvgAggregateOutputType | null
  _sum: BacktestSumAggregateOutputType | null
  _min: BacktestMinAggregateOutputType | null
  _max: BacktestMaxAggregateOutputType | null
}

export type BacktestAvgAggregateOutputType = {
  pnlPercent: number | null
  numTrades: number | null
  winRate: number | null
  maxDrawdown: number | null
}

export type BacktestSumAggregateOutputType = {
  pnlPercent: number | null
  numTrades: number | null
  winRate: number | null
  maxDrawdown: number | null
}

export type BacktestMinAggregateOutputType = {
  id: string | null
  strategyId: string | null
  userId: string | null
  timeframe: string | null
  fromDate: Date | null
  toDate: Date | null
  pnlPercent: number | null
  numTrades: number | null
  winRate: number | null
  maxDrawdown: number | null
}

export type BacktestMaxAggregateOutputType = {
  id: string | null
  strategyId: string | null
  userId: string | null
  timeframe: string | null
  fromDate: Date | null
  toDate: Date | null
  pnlPercent: number | null
  numTrades: number | null
  winRate: number | null
  maxDrawdown: number | null
}

export type BacktestCountAggregateOutputType = {
  id: number
  strategyId: number
  userId: number
  timeframe: number
  fromDate: number
  toDate: number
  pnlPercent: number
  numTrades: number
  winRate: number
  maxDrawdown: number
  _all: number
}


export type BacktestAvgAggregateInputType = {
  pnlPercent?: true
  numTrades?: true
  winRate?: true
  maxDrawdown?: true
}

export type BacktestSumAggregateInputType = {
  pnlPercent?: true
  numTrades?: true
  winRate?: true
  maxDrawdown?: true
}

export type BacktestMinAggregateInputType = {
  id?: true
  strategyId?: true
  userId?: true
  timeframe?: true
  fromDate?: true
  toDate?: true
  pnlPercent?: true
  numTrades?: true
  winRate?: true
  maxDrawdown?: true
}

export type BacktestMaxAggregateInputType = {
  id?: true
  strategyId?: true
  userId?: true
  timeframe?: true
  fromDate?: true
  toDate?: true
  pnlPercent?: true
  numTrades?: true
  winRate?: true
  maxDrawdown?: true
}

export type BacktestCountAggregateInputType = {
  id?: true
  strategyId?: true
  userId?: true
  timeframe?: true
  fromDate?: true
  toDate?: true
  pnlPercent?: true
  numTrades?: true
  winRate?: true
  maxDrawdown?: true
  _all?: true
}

export type BacktestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Backtest to aggregate.
   */
  where?: Prisma.BacktestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Backtests to fetch.
   */
  orderBy?: Prisma.BacktestOrderByWithRelationInput | Prisma.BacktestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BacktestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Backtests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Backtests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Backtests
  **/
  _count?: true | BacktestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BacktestAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BacktestSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BacktestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BacktestMaxAggregateInputType
}

export type GetBacktestAggregateType<T extends BacktestAggregateArgs> = {
      [P in keyof T & keyof AggregateBacktest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBacktest[P]>
    : Prisma.GetScalarType<T[P], AggregateBacktest[P]>
}




export type BacktestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BacktestWhereInput
  orderBy?: Prisma.BacktestOrderByWithAggregationInput | Prisma.BacktestOrderByWithAggregationInput[]
  by: Prisma.BacktestScalarFieldEnum[] | Prisma.BacktestScalarFieldEnum
  having?: Prisma.BacktestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BacktestCountAggregateInputType | true
  _avg?: BacktestAvgAggregateInputType
  _sum?: BacktestSumAggregateInputType
  _min?: BacktestMinAggregateInputType
  _max?: BacktestMaxAggregateInputType
}

export type BacktestGroupByOutputType = {
  id: string
  strategyId: string
  userId: string
  timeframe: string
  fromDate: Date
  toDate: Date
  pnlPercent: number
  numTrades: number
  winRate: number | null
  maxDrawdown: number | null
  _count: BacktestCountAggregateOutputType | null
  _avg: BacktestAvgAggregateOutputType | null
  _sum: BacktestSumAggregateOutputType | null
  _min: BacktestMinAggregateOutputType | null
  _max: BacktestMaxAggregateOutputType | null
}

type GetBacktestGroupByPayload<T extends BacktestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BacktestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BacktestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BacktestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BacktestGroupByOutputType[P]>
      }
    >
  >



export type BacktestWhereInput = {
  AND?: Prisma.BacktestWhereInput | Prisma.BacktestWhereInput[]
  OR?: Prisma.BacktestWhereInput[]
  NOT?: Prisma.BacktestWhereInput | Prisma.BacktestWhereInput[]
  id?: Prisma.StringFilter<"Backtest"> | string
  strategyId?: Prisma.StringFilter<"Backtest"> | string
  userId?: Prisma.StringFilter<"Backtest"> | string
  timeframe?: Prisma.StringFilter<"Backtest"> | string
  fromDate?: Prisma.DateTimeFilter<"Backtest"> | Date | string
  toDate?: Prisma.DateTimeFilter<"Backtest"> | Date | string
  pnlPercent?: Prisma.FloatFilter<"Backtest"> | number
  numTrades?: Prisma.IntFilter<"Backtest"> | number
  winRate?: Prisma.FloatNullableFilter<"Backtest"> | number | null
  maxDrawdown?: Prisma.FloatNullableFilter<"Backtest"> | number | null
  strategy?: Prisma.XOR<Prisma.StrategyScalarRelationFilter, Prisma.StrategyWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type BacktestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  fromDate?: Prisma.SortOrder
  toDate?: Prisma.SortOrder
  pnlPercent?: Prisma.SortOrder
  numTrades?: Prisma.SortOrder
  winRate?: Prisma.SortOrderInput | Prisma.SortOrder
  maxDrawdown?: Prisma.SortOrderInput | Prisma.SortOrder
  strategy?: Prisma.StrategyOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type BacktestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BacktestWhereInput | Prisma.BacktestWhereInput[]
  OR?: Prisma.BacktestWhereInput[]
  NOT?: Prisma.BacktestWhereInput | Prisma.BacktestWhereInput[]
  strategyId?: Prisma.StringFilter<"Backtest"> | string
  userId?: Prisma.StringFilter<"Backtest"> | string
  timeframe?: Prisma.StringFilter<"Backtest"> | string
  fromDate?: Prisma.DateTimeFilter<"Backtest"> | Date | string
  toDate?: Prisma.DateTimeFilter<"Backtest"> | Date | string
  pnlPercent?: Prisma.FloatFilter<"Backtest"> | number
  numTrades?: Prisma.IntFilter<"Backtest"> | number
  winRate?: Prisma.FloatNullableFilter<"Backtest"> | number | null
  maxDrawdown?: Prisma.FloatNullableFilter<"Backtest"> | number | null
  strategy?: Prisma.XOR<Prisma.StrategyScalarRelationFilter, Prisma.StrategyWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type BacktestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  fromDate?: Prisma.SortOrder
  toDate?: Prisma.SortOrder
  pnlPercent?: Prisma.SortOrder
  numTrades?: Prisma.SortOrder
  winRate?: Prisma.SortOrderInput | Prisma.SortOrder
  maxDrawdown?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BacktestCountOrderByAggregateInput
  _avg?: Prisma.BacktestAvgOrderByAggregateInput
  _max?: Prisma.BacktestMaxOrderByAggregateInput
  _min?: Prisma.BacktestMinOrderByAggregateInput
  _sum?: Prisma.BacktestSumOrderByAggregateInput
}

export type BacktestScalarWhereWithAggregatesInput = {
  AND?: Prisma.BacktestScalarWhereWithAggregatesInput | Prisma.BacktestScalarWhereWithAggregatesInput[]
  OR?: Prisma.BacktestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BacktestScalarWhereWithAggregatesInput | Prisma.BacktestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Backtest"> | string
  strategyId?: Prisma.StringWithAggregatesFilter<"Backtest"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Backtest"> | string
  timeframe?: Prisma.StringWithAggregatesFilter<"Backtest"> | string
  fromDate?: Prisma.DateTimeWithAggregatesFilter<"Backtest"> | Date | string
  toDate?: Prisma.DateTimeWithAggregatesFilter<"Backtest"> | Date | string
  pnlPercent?: Prisma.FloatWithAggregatesFilter<"Backtest"> | number
  numTrades?: Prisma.IntWithAggregatesFilter<"Backtest"> | number
  winRate?: Prisma.FloatNullableWithAggregatesFilter<"Backtest"> | number | null
  maxDrawdown?: Prisma.FloatNullableWithAggregatesFilter<"Backtest"> | number | null
}

export type BacktestCreateInput = {
  id?: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
  strategy: Prisma.StrategyCreateNestedOneWithoutBacktestsInput
  user: Prisma.UserCreateNestedOneWithoutBacktestsInput
}

export type BacktestUncheckedCreateInput = {
  id?: string
  strategyId: string
  userId: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
}

export type BacktestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  strategy?: Prisma.StrategyUpdateOneRequiredWithoutBacktestsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutBacktestsNestedInput
}

export type BacktestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type BacktestCreateManyInput = {
  id?: string
  strategyId: string
  userId: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
}

export type BacktestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type BacktestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type BacktestListRelationFilter = {
  every?: Prisma.BacktestWhereInput
  some?: Prisma.BacktestWhereInput
  none?: Prisma.BacktestWhereInput
}

export type BacktestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BacktestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  fromDate?: Prisma.SortOrder
  toDate?: Prisma.SortOrder
  pnlPercent?: Prisma.SortOrder
  numTrades?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  maxDrawdown?: Prisma.SortOrder
}

export type BacktestAvgOrderByAggregateInput = {
  pnlPercent?: Prisma.SortOrder
  numTrades?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  maxDrawdown?: Prisma.SortOrder
}

export type BacktestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  fromDate?: Prisma.SortOrder
  toDate?: Prisma.SortOrder
  pnlPercent?: Prisma.SortOrder
  numTrades?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  maxDrawdown?: Prisma.SortOrder
}

export type BacktestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  fromDate?: Prisma.SortOrder
  toDate?: Prisma.SortOrder
  pnlPercent?: Prisma.SortOrder
  numTrades?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  maxDrawdown?: Prisma.SortOrder
}

export type BacktestSumOrderByAggregateInput = {
  pnlPercent?: Prisma.SortOrder
  numTrades?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  maxDrawdown?: Prisma.SortOrder
}

export type BacktestCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutUserInput, Prisma.BacktestUncheckedCreateWithoutUserInput> | Prisma.BacktestCreateWithoutUserInput[] | Prisma.BacktestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutUserInput | Prisma.BacktestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BacktestCreateManyUserInputEnvelope
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
}

export type BacktestUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutUserInput, Prisma.BacktestUncheckedCreateWithoutUserInput> | Prisma.BacktestCreateWithoutUserInput[] | Prisma.BacktestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutUserInput | Prisma.BacktestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BacktestCreateManyUserInputEnvelope
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
}

export type BacktestUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutUserInput, Prisma.BacktestUncheckedCreateWithoutUserInput> | Prisma.BacktestCreateWithoutUserInput[] | Prisma.BacktestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutUserInput | Prisma.BacktestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BacktestUpsertWithWhereUniqueWithoutUserInput | Prisma.BacktestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BacktestCreateManyUserInputEnvelope
  set?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  disconnect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  delete?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  update?: Prisma.BacktestUpdateWithWhereUniqueWithoutUserInput | Prisma.BacktestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BacktestUpdateManyWithWhereWithoutUserInput | Prisma.BacktestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BacktestScalarWhereInput | Prisma.BacktestScalarWhereInput[]
}

export type BacktestUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutUserInput, Prisma.BacktestUncheckedCreateWithoutUserInput> | Prisma.BacktestCreateWithoutUserInput[] | Prisma.BacktestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutUserInput | Prisma.BacktestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BacktestUpsertWithWhereUniqueWithoutUserInput | Prisma.BacktestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BacktestCreateManyUserInputEnvelope
  set?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  disconnect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  delete?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  update?: Prisma.BacktestUpdateWithWhereUniqueWithoutUserInput | Prisma.BacktestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BacktestUpdateManyWithWhereWithoutUserInput | Prisma.BacktestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BacktestScalarWhereInput | Prisma.BacktestScalarWhereInput[]
}

export type BacktestCreateNestedManyWithoutStrategyInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutStrategyInput, Prisma.BacktestUncheckedCreateWithoutStrategyInput> | Prisma.BacktestCreateWithoutStrategyInput[] | Prisma.BacktestUncheckedCreateWithoutStrategyInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutStrategyInput | Prisma.BacktestCreateOrConnectWithoutStrategyInput[]
  createMany?: Prisma.BacktestCreateManyStrategyInputEnvelope
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
}

export type BacktestUncheckedCreateNestedManyWithoutStrategyInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutStrategyInput, Prisma.BacktestUncheckedCreateWithoutStrategyInput> | Prisma.BacktestCreateWithoutStrategyInput[] | Prisma.BacktestUncheckedCreateWithoutStrategyInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutStrategyInput | Prisma.BacktestCreateOrConnectWithoutStrategyInput[]
  createMany?: Prisma.BacktestCreateManyStrategyInputEnvelope
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
}

export type BacktestUpdateManyWithoutStrategyNestedInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutStrategyInput, Prisma.BacktestUncheckedCreateWithoutStrategyInput> | Prisma.BacktestCreateWithoutStrategyInput[] | Prisma.BacktestUncheckedCreateWithoutStrategyInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutStrategyInput | Prisma.BacktestCreateOrConnectWithoutStrategyInput[]
  upsert?: Prisma.BacktestUpsertWithWhereUniqueWithoutStrategyInput | Prisma.BacktestUpsertWithWhereUniqueWithoutStrategyInput[]
  createMany?: Prisma.BacktestCreateManyStrategyInputEnvelope
  set?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  disconnect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  delete?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  update?: Prisma.BacktestUpdateWithWhereUniqueWithoutStrategyInput | Prisma.BacktestUpdateWithWhereUniqueWithoutStrategyInput[]
  updateMany?: Prisma.BacktestUpdateManyWithWhereWithoutStrategyInput | Prisma.BacktestUpdateManyWithWhereWithoutStrategyInput[]
  deleteMany?: Prisma.BacktestScalarWhereInput | Prisma.BacktestScalarWhereInput[]
}

export type BacktestUncheckedUpdateManyWithoutStrategyNestedInput = {
  create?: Prisma.XOR<Prisma.BacktestCreateWithoutStrategyInput, Prisma.BacktestUncheckedCreateWithoutStrategyInput> | Prisma.BacktestCreateWithoutStrategyInput[] | Prisma.BacktestUncheckedCreateWithoutStrategyInput[]
  connectOrCreate?: Prisma.BacktestCreateOrConnectWithoutStrategyInput | Prisma.BacktestCreateOrConnectWithoutStrategyInput[]
  upsert?: Prisma.BacktestUpsertWithWhereUniqueWithoutStrategyInput | Prisma.BacktestUpsertWithWhereUniqueWithoutStrategyInput[]
  createMany?: Prisma.BacktestCreateManyStrategyInputEnvelope
  set?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  disconnect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  delete?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  connect?: Prisma.BacktestWhereUniqueInput | Prisma.BacktestWhereUniqueInput[]
  update?: Prisma.BacktestUpdateWithWhereUniqueWithoutStrategyInput | Prisma.BacktestUpdateWithWhereUniqueWithoutStrategyInput[]
  updateMany?: Prisma.BacktestUpdateManyWithWhereWithoutStrategyInput | Prisma.BacktestUpdateManyWithWhereWithoutStrategyInput[]
  deleteMany?: Prisma.BacktestScalarWhereInput | Prisma.BacktestScalarWhereInput[]
}

export type BacktestCreateWithoutUserInput = {
  id?: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
  strategy: Prisma.StrategyCreateNestedOneWithoutBacktestsInput
}

export type BacktestUncheckedCreateWithoutUserInput = {
  id?: string
  strategyId: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
}

export type BacktestCreateOrConnectWithoutUserInput = {
  where: Prisma.BacktestWhereUniqueInput
  create: Prisma.XOR<Prisma.BacktestCreateWithoutUserInput, Prisma.BacktestUncheckedCreateWithoutUserInput>
}

export type BacktestCreateManyUserInputEnvelope = {
  data: Prisma.BacktestCreateManyUserInput | Prisma.BacktestCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BacktestUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BacktestWhereUniqueInput
  update: Prisma.XOR<Prisma.BacktestUpdateWithoutUserInput, Prisma.BacktestUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BacktestCreateWithoutUserInput, Prisma.BacktestUncheckedCreateWithoutUserInput>
}

export type BacktestUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BacktestWhereUniqueInput
  data: Prisma.XOR<Prisma.BacktestUpdateWithoutUserInput, Prisma.BacktestUncheckedUpdateWithoutUserInput>
}

export type BacktestUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BacktestScalarWhereInput
  data: Prisma.XOR<Prisma.BacktestUpdateManyMutationInput, Prisma.BacktestUncheckedUpdateManyWithoutUserInput>
}

export type BacktestScalarWhereInput = {
  AND?: Prisma.BacktestScalarWhereInput | Prisma.BacktestScalarWhereInput[]
  OR?: Prisma.BacktestScalarWhereInput[]
  NOT?: Prisma.BacktestScalarWhereInput | Prisma.BacktestScalarWhereInput[]
  id?: Prisma.StringFilter<"Backtest"> | string
  strategyId?: Prisma.StringFilter<"Backtest"> | string
  userId?: Prisma.StringFilter<"Backtest"> | string
  timeframe?: Prisma.StringFilter<"Backtest"> | string
  fromDate?: Prisma.DateTimeFilter<"Backtest"> | Date | string
  toDate?: Prisma.DateTimeFilter<"Backtest"> | Date | string
  pnlPercent?: Prisma.FloatFilter<"Backtest"> | number
  numTrades?: Prisma.IntFilter<"Backtest"> | number
  winRate?: Prisma.FloatNullableFilter<"Backtest"> | number | null
  maxDrawdown?: Prisma.FloatNullableFilter<"Backtest"> | number | null
}

export type BacktestCreateWithoutStrategyInput = {
  id?: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
  user: Prisma.UserCreateNestedOneWithoutBacktestsInput
}

export type BacktestUncheckedCreateWithoutStrategyInput = {
  id?: string
  userId: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
}

export type BacktestCreateOrConnectWithoutStrategyInput = {
  where: Prisma.BacktestWhereUniqueInput
  create: Prisma.XOR<Prisma.BacktestCreateWithoutStrategyInput, Prisma.BacktestUncheckedCreateWithoutStrategyInput>
}

export type BacktestCreateManyStrategyInputEnvelope = {
  data: Prisma.BacktestCreateManyStrategyInput | Prisma.BacktestCreateManyStrategyInput[]
  skipDuplicates?: boolean
}

export type BacktestUpsertWithWhereUniqueWithoutStrategyInput = {
  where: Prisma.BacktestWhereUniqueInput
  update: Prisma.XOR<Prisma.BacktestUpdateWithoutStrategyInput, Prisma.BacktestUncheckedUpdateWithoutStrategyInput>
  create: Prisma.XOR<Prisma.BacktestCreateWithoutStrategyInput, Prisma.BacktestUncheckedCreateWithoutStrategyInput>
}

export type BacktestUpdateWithWhereUniqueWithoutStrategyInput = {
  where: Prisma.BacktestWhereUniqueInput
  data: Prisma.XOR<Prisma.BacktestUpdateWithoutStrategyInput, Prisma.BacktestUncheckedUpdateWithoutStrategyInput>
}

export type BacktestUpdateManyWithWhereWithoutStrategyInput = {
  where: Prisma.BacktestScalarWhereInput
  data: Prisma.XOR<Prisma.BacktestUpdateManyMutationInput, Prisma.BacktestUncheckedUpdateManyWithoutStrategyInput>
}

export type BacktestCreateManyUserInput = {
  id?: string
  strategyId: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
}

export type BacktestUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  strategy?: Prisma.StrategyUpdateOneRequiredWithoutBacktestsNestedInput
}

export type BacktestUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type BacktestUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type BacktestCreateManyStrategyInput = {
  id?: string
  userId: string
  timeframe: string
  fromDate: Date | string
  toDate: Date | string
  pnlPercent: number
  numTrades: number
  winRate?: number | null
  maxDrawdown?: number | null
}

export type BacktestUpdateWithoutStrategyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  user?: Prisma.UserUpdateOneRequiredWithoutBacktestsNestedInput
}

export type BacktestUncheckedUpdateWithoutStrategyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type BacktestUncheckedUpdateManyWithoutStrategyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  fromDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pnlPercent?: Prisma.FloatFieldUpdateOperationsInput | number
  numTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  maxDrawdown?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}



export type BacktestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  strategyId?: boolean
  userId?: boolean
  timeframe?: boolean
  fromDate?: boolean
  toDate?: boolean
  pnlPercent?: boolean
  numTrades?: boolean
  winRate?: boolean
  maxDrawdown?: boolean
  strategy?: boolean | Prisma.StrategyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["backtest"]>

export type BacktestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  strategyId?: boolean
  userId?: boolean
  timeframe?: boolean
  fromDate?: boolean
  toDate?: boolean
  pnlPercent?: boolean
  numTrades?: boolean
  winRate?: boolean
  maxDrawdown?: boolean
  strategy?: boolean | Prisma.StrategyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["backtest"]>

export type BacktestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  strategyId?: boolean
  userId?: boolean
  timeframe?: boolean
  fromDate?: boolean
  toDate?: boolean
  pnlPercent?: boolean
  numTrades?: boolean
  winRate?: boolean
  maxDrawdown?: boolean
  strategy?: boolean | Prisma.StrategyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["backtest"]>

export type BacktestSelectScalar = {
  id?: boolean
  strategyId?: boolean
  userId?: boolean
  timeframe?: boolean
  fromDate?: boolean
  toDate?: boolean
  pnlPercent?: boolean
  numTrades?: boolean
  winRate?: boolean
  maxDrawdown?: boolean
}

export type BacktestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "strategyId" | "userId" | "timeframe" | "fromDate" | "toDate" | "pnlPercent" | "numTrades" | "winRate" | "maxDrawdown", ExtArgs["result"]["backtest"]>
export type BacktestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  strategy?: boolean | Prisma.StrategyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BacktestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  strategy?: boolean | Prisma.StrategyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BacktestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  strategy?: boolean | Prisma.StrategyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BacktestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Backtest"
  objects: {
    strategy: Prisma.$StrategyPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    strategyId: string
    userId: string
    timeframe: string
    fromDate: Date
    toDate: Date
    pnlPercent: number
    numTrades: number
    winRate: number | null
    maxDrawdown: number | null
  }, ExtArgs["result"]["backtest"]>
  composites: {}
}

export type BacktestGetPayload<S extends boolean | null | undefined | BacktestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BacktestPayload, S>

export type BacktestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BacktestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BacktestCountAggregateInputType | true
  }

export interface BacktestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Backtest'], meta: { name: 'Backtest' } }
  /**
   * Find zero or one Backtest that matches the filter.
   * @param {BacktestFindUniqueArgs} args - Arguments to find a Backtest
   * @example
   * // Get one Backtest
   * const backtest = await prisma.backtest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BacktestFindUniqueArgs>(args: Prisma.SelectSubset<T, BacktestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Backtest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BacktestFindUniqueOrThrowArgs} args - Arguments to find a Backtest
   * @example
   * // Get one Backtest
   * const backtest = await prisma.backtest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BacktestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BacktestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Backtest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BacktestFindFirstArgs} args - Arguments to find a Backtest
   * @example
   * // Get one Backtest
   * const backtest = await prisma.backtest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BacktestFindFirstArgs>(args?: Prisma.SelectSubset<T, BacktestFindFirstArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Backtest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BacktestFindFirstOrThrowArgs} args - Arguments to find a Backtest
   * @example
   * // Get one Backtest
   * const backtest = await prisma.backtest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BacktestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BacktestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Backtests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BacktestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Backtests
   * const backtests = await prisma.backtest.findMany()
   * 
   * // Get first 10 Backtests
   * const backtests = await prisma.backtest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const backtestWithIdOnly = await prisma.backtest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BacktestFindManyArgs>(args?: Prisma.SelectSubset<T, BacktestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Backtest.
   * @param {BacktestCreateArgs} args - Arguments to create a Backtest.
   * @example
   * // Create one Backtest
   * const Backtest = await prisma.backtest.create({
   *   data: {
   *     // ... data to create a Backtest
   *   }
   * })
   * 
   */
  create<T extends BacktestCreateArgs>(args: Prisma.SelectSubset<T, BacktestCreateArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Backtests.
   * @param {BacktestCreateManyArgs} args - Arguments to create many Backtests.
   * @example
   * // Create many Backtests
   * const backtest = await prisma.backtest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BacktestCreateManyArgs>(args?: Prisma.SelectSubset<T, BacktestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Backtests and returns the data saved in the database.
   * @param {BacktestCreateManyAndReturnArgs} args - Arguments to create many Backtests.
   * @example
   * // Create many Backtests
   * const backtest = await prisma.backtest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Backtests and only return the `id`
   * const backtestWithIdOnly = await prisma.backtest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BacktestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BacktestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Backtest.
   * @param {BacktestDeleteArgs} args - Arguments to delete one Backtest.
   * @example
   * // Delete one Backtest
   * const Backtest = await prisma.backtest.delete({
   *   where: {
   *     // ... filter to delete one Backtest
   *   }
   * })
   * 
   */
  delete<T extends BacktestDeleteArgs>(args: Prisma.SelectSubset<T, BacktestDeleteArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Backtest.
   * @param {BacktestUpdateArgs} args - Arguments to update one Backtest.
   * @example
   * // Update one Backtest
   * const backtest = await prisma.backtest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BacktestUpdateArgs>(args: Prisma.SelectSubset<T, BacktestUpdateArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Backtests.
   * @param {BacktestDeleteManyArgs} args - Arguments to filter Backtests to delete.
   * @example
   * // Delete a few Backtests
   * const { count } = await prisma.backtest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BacktestDeleteManyArgs>(args?: Prisma.SelectSubset<T, BacktestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Backtests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BacktestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Backtests
   * const backtest = await prisma.backtest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BacktestUpdateManyArgs>(args: Prisma.SelectSubset<T, BacktestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Backtests and returns the data updated in the database.
   * @param {BacktestUpdateManyAndReturnArgs} args - Arguments to update many Backtests.
   * @example
   * // Update many Backtests
   * const backtest = await prisma.backtest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Backtests and only return the `id`
   * const backtestWithIdOnly = await prisma.backtest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BacktestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BacktestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Backtest.
   * @param {BacktestUpsertArgs} args - Arguments to update or create a Backtest.
   * @example
   * // Update or create a Backtest
   * const backtest = await prisma.backtest.upsert({
   *   create: {
   *     // ... data to create a Backtest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Backtest we want to update
   *   }
   * })
   */
  upsert<T extends BacktestUpsertArgs>(args: Prisma.SelectSubset<T, BacktestUpsertArgs<ExtArgs>>): Prisma.Prisma__BacktestClient<runtime.Types.Result.GetResult<Prisma.$BacktestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Backtests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BacktestCountArgs} args - Arguments to filter Backtests to count.
   * @example
   * // Count the number of Backtests
   * const count = await prisma.backtest.count({
   *   where: {
   *     // ... the filter for the Backtests we want to count
   *   }
   * })
  **/
  count<T extends BacktestCountArgs>(
    args?: Prisma.Subset<T, BacktestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BacktestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Backtest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BacktestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BacktestAggregateArgs>(args: Prisma.Subset<T, BacktestAggregateArgs>): Prisma.PrismaPromise<GetBacktestAggregateType<T>>

  /**
   * Group by Backtest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BacktestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BacktestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BacktestGroupByArgs['orderBy'] }
      : { orderBy?: BacktestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BacktestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBacktestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Backtest model
 */
readonly fields: BacktestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Backtest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BacktestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  strategy<T extends Prisma.StrategyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StrategyDefaultArgs<ExtArgs>>): Prisma.Prisma__StrategyClient<runtime.Types.Result.GetResult<Prisma.$StrategyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Backtest model
 */
export interface BacktestFieldRefs {
  readonly id: Prisma.FieldRef<"Backtest", 'String'>
  readonly strategyId: Prisma.FieldRef<"Backtest", 'String'>
  readonly userId: Prisma.FieldRef<"Backtest", 'String'>
  readonly timeframe: Prisma.FieldRef<"Backtest", 'String'>
  readonly fromDate: Prisma.FieldRef<"Backtest", 'DateTime'>
  readonly toDate: Prisma.FieldRef<"Backtest", 'DateTime'>
  readonly pnlPercent: Prisma.FieldRef<"Backtest", 'Float'>
  readonly numTrades: Prisma.FieldRef<"Backtest", 'Int'>
  readonly winRate: Prisma.FieldRef<"Backtest", 'Float'>
  readonly maxDrawdown: Prisma.FieldRef<"Backtest", 'Float'>
}
    

// Custom InputTypes
/**
 * Backtest findUnique
 */
export type BacktestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * Filter, which Backtest to fetch.
   */
  where: Prisma.BacktestWhereUniqueInput
}

/**
 * Backtest findUniqueOrThrow
 */
export type BacktestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * Filter, which Backtest to fetch.
   */
  where: Prisma.BacktestWhereUniqueInput
}

/**
 * Backtest findFirst
 */
export type BacktestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * Filter, which Backtest to fetch.
   */
  where?: Prisma.BacktestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Backtests to fetch.
   */
  orderBy?: Prisma.BacktestOrderByWithRelationInput | Prisma.BacktestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Backtests.
   */
  cursor?: Prisma.BacktestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Backtests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Backtests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Backtests.
   */
  distinct?: Prisma.BacktestScalarFieldEnum | Prisma.BacktestScalarFieldEnum[]
}

/**
 * Backtest findFirstOrThrow
 */
export type BacktestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * Filter, which Backtest to fetch.
   */
  where?: Prisma.BacktestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Backtests to fetch.
   */
  orderBy?: Prisma.BacktestOrderByWithRelationInput | Prisma.BacktestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Backtests.
   */
  cursor?: Prisma.BacktestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Backtests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Backtests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Backtests.
   */
  distinct?: Prisma.BacktestScalarFieldEnum | Prisma.BacktestScalarFieldEnum[]
}

/**
 * Backtest findMany
 */
export type BacktestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * Filter, which Backtests to fetch.
   */
  where?: Prisma.BacktestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Backtests to fetch.
   */
  orderBy?: Prisma.BacktestOrderByWithRelationInput | Prisma.BacktestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Backtests.
   */
  cursor?: Prisma.BacktestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Backtests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Backtests.
   */
  skip?: number
  distinct?: Prisma.BacktestScalarFieldEnum | Prisma.BacktestScalarFieldEnum[]
}

/**
 * Backtest create
 */
export type BacktestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * The data needed to create a Backtest.
   */
  data: Prisma.XOR<Prisma.BacktestCreateInput, Prisma.BacktestUncheckedCreateInput>
}

/**
 * Backtest createMany
 */
export type BacktestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Backtests.
   */
  data: Prisma.BacktestCreateManyInput | Prisma.BacktestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Backtest createManyAndReturn
 */
export type BacktestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * The data used to create many Backtests.
   */
  data: Prisma.BacktestCreateManyInput | Prisma.BacktestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Backtest update
 */
export type BacktestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * The data needed to update a Backtest.
   */
  data: Prisma.XOR<Prisma.BacktestUpdateInput, Prisma.BacktestUncheckedUpdateInput>
  /**
   * Choose, which Backtest to update.
   */
  where: Prisma.BacktestWhereUniqueInput
}

/**
 * Backtest updateMany
 */
export type BacktestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Backtests.
   */
  data: Prisma.XOR<Prisma.BacktestUpdateManyMutationInput, Prisma.BacktestUncheckedUpdateManyInput>
  /**
   * Filter which Backtests to update
   */
  where?: Prisma.BacktestWhereInput
  /**
   * Limit how many Backtests to update.
   */
  limit?: number
}

/**
 * Backtest updateManyAndReturn
 */
export type BacktestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * The data used to update Backtests.
   */
  data: Prisma.XOR<Prisma.BacktestUpdateManyMutationInput, Prisma.BacktestUncheckedUpdateManyInput>
  /**
   * Filter which Backtests to update
   */
  where?: Prisma.BacktestWhereInput
  /**
   * Limit how many Backtests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Backtest upsert
 */
export type BacktestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * The filter to search for the Backtest to update in case it exists.
   */
  where: Prisma.BacktestWhereUniqueInput
  /**
   * In case the Backtest found by the `where` argument doesn't exist, create a new Backtest with this data.
   */
  create: Prisma.XOR<Prisma.BacktestCreateInput, Prisma.BacktestUncheckedCreateInput>
  /**
   * In case the Backtest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BacktestUpdateInput, Prisma.BacktestUncheckedUpdateInput>
}

/**
 * Backtest delete
 */
export type BacktestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
  /**
   * Filter which Backtest to delete.
   */
  where: Prisma.BacktestWhereUniqueInput
}

/**
 * Backtest deleteMany
 */
export type BacktestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Backtests to delete
   */
  where?: Prisma.BacktestWhereInput
  /**
   * Limit how many Backtests to delete.
   */
  limit?: number
}

/**
 * Backtest without action
 */
export type BacktestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Backtest
   */
  select?: Prisma.BacktestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Backtest
   */
  omit?: Prisma.BacktestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BacktestInclude<ExtArgs> | null
}
