
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Coin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Coin
 * 
 */
export type CoinModel = runtime.Types.Result.DefaultSelection<Prisma.$CoinPayload>

export type AggregateCoin = {
  _count: CoinCountAggregateOutputType | null
  _min: CoinMinAggregateOutputType | null
  _max: CoinMaxAggregateOutputType | null
}

export type CoinMinAggregateOutputType = {
  id: string | null
  name: string | null
  symbol: string | null
  image: string | null
}

export type CoinMaxAggregateOutputType = {
  id: string | null
  name: string | null
  symbol: string | null
  image: string | null
}

export type CoinCountAggregateOutputType = {
  id: number
  name: number
  symbol: number
  image: number
  _all: number
}


export type CoinMinAggregateInputType = {
  id?: true
  name?: true
  symbol?: true
  image?: true
}

export type CoinMaxAggregateInputType = {
  id?: true
  name?: true
  symbol?: true
  image?: true
}

export type CoinCountAggregateInputType = {
  id?: true
  name?: true
  symbol?: true
  image?: true
  _all?: true
}

export type CoinAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Coin to aggregate.
   */
  where?: Prisma.CoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Coins to fetch.
   */
  orderBy?: Prisma.CoinOrderByWithRelationInput | Prisma.CoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Coins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Coins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Coins
  **/
  _count?: true | CoinCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CoinMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CoinMaxAggregateInputType
}

export type GetCoinAggregateType<T extends CoinAggregateArgs> = {
      [P in keyof T & keyof AggregateCoin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCoin[P]>
    : Prisma.GetScalarType<T[P], AggregateCoin[P]>
}




export type CoinGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CoinWhereInput
  orderBy?: Prisma.CoinOrderByWithAggregationInput | Prisma.CoinOrderByWithAggregationInput[]
  by: Prisma.CoinScalarFieldEnum[] | Prisma.CoinScalarFieldEnum
  having?: Prisma.CoinScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CoinCountAggregateInputType | true
  _min?: CoinMinAggregateInputType
  _max?: CoinMaxAggregateInputType
}

export type CoinGroupByOutputType = {
  id: string
  name: string
  symbol: string
  image: string | null
  _count: CoinCountAggregateOutputType | null
  _min: CoinMinAggregateOutputType | null
  _max: CoinMaxAggregateOutputType | null
}

type GetCoinGroupByPayload<T extends CoinGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CoinGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CoinGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CoinGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CoinGroupByOutputType[P]>
      }
    >
  >



export type CoinWhereInput = {
  AND?: Prisma.CoinWhereInput | Prisma.CoinWhereInput[]
  OR?: Prisma.CoinWhereInput[]
  NOT?: Prisma.CoinWhereInput | Prisma.CoinWhereInput[]
  id?: Prisma.StringFilter<"Coin"> | string
  name?: Prisma.StringFilter<"Coin"> | string
  symbol?: Prisma.StringFilter<"Coin"> | string
  image?: Prisma.StringNullableFilter<"Coin"> | string | null
  balances?: Prisma.BalanceListRelationFilter
  portfolioHistory?: Prisma.PortfolioHistoryListRelationFilter
  strategies?: Prisma.StrategyListRelationFilter
  trades?: Prisma.TradeListRelationFilter
  userCoins?: Prisma.UserCoinListRelationFilter
  walletTradesFrom?: Prisma.WalletTradeListRelationFilter
  walletTradesTo?: Prisma.WalletTradeListRelationFilter
}

export type CoinOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  balances?: Prisma.BalanceOrderByRelationAggregateInput
  portfolioHistory?: Prisma.PortfolioHistoryOrderByRelationAggregateInput
  strategies?: Prisma.StrategyOrderByRelationAggregateInput
  trades?: Prisma.TradeOrderByRelationAggregateInput
  userCoins?: Prisma.UserCoinOrderByRelationAggregateInput
  walletTradesFrom?: Prisma.WalletTradeOrderByRelationAggregateInput
  walletTradesTo?: Prisma.WalletTradeOrderByRelationAggregateInput
}

export type CoinWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CoinWhereInput | Prisma.CoinWhereInput[]
  OR?: Prisma.CoinWhereInput[]
  NOT?: Prisma.CoinWhereInput | Prisma.CoinWhereInput[]
  name?: Prisma.StringFilter<"Coin"> | string
  symbol?: Prisma.StringFilter<"Coin"> | string
  image?: Prisma.StringNullableFilter<"Coin"> | string | null
  balances?: Prisma.BalanceListRelationFilter
  portfolioHistory?: Prisma.PortfolioHistoryListRelationFilter
  strategies?: Prisma.StrategyListRelationFilter
  trades?: Prisma.TradeListRelationFilter
  userCoins?: Prisma.UserCoinListRelationFilter
  walletTradesFrom?: Prisma.WalletTradeListRelationFilter
  walletTradesTo?: Prisma.WalletTradeListRelationFilter
}, "id">

export type CoinOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CoinCountOrderByAggregateInput
  _max?: Prisma.CoinMaxOrderByAggregateInput
  _min?: Prisma.CoinMinOrderByAggregateInput
}

export type CoinScalarWhereWithAggregatesInput = {
  AND?: Prisma.CoinScalarWhereWithAggregatesInput | Prisma.CoinScalarWhereWithAggregatesInput[]
  OR?: Prisma.CoinScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CoinScalarWhereWithAggregatesInput | Prisma.CoinScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Coin"> | string
  name?: Prisma.StringWithAggregatesFilter<"Coin"> | string
  symbol?: Prisma.StringWithAggregatesFilter<"Coin"> | string
  image?: Prisma.StringNullableWithAggregatesFilter<"Coin"> | string | null
}

export type CoinCreateInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeCreateNestedManyWithoutToCoinInput
}

export type CoinUncheckedCreateInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceUncheckedCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyUncheckedCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinUncheckedCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutToCoinInput
}

export type CoinUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUpdateManyWithoutToCoinNestedInput
}

export type CoinUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUncheckedUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUncheckedUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUncheckedUpdateManyWithoutToCoinNestedInput
}

export type CoinCreateManyInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
}

export type CoinUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CoinUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CoinScalarRelationFilter = {
  is?: Prisma.CoinWhereInput
  isNot?: Prisma.CoinWhereInput
}

export type CoinNullableScalarRelationFilter = {
  is?: Prisma.CoinWhereInput | null
  isNot?: Prisma.CoinWhereInput | null
}

export type CoinCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  image?: Prisma.SortOrder
}

export type CoinMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  image?: Prisma.SortOrder
}

export type CoinMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  image?: Prisma.SortOrder
}

export type CoinCreateNestedOneWithoutUserCoinsInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutUserCoinsInput, Prisma.CoinUncheckedCreateWithoutUserCoinsInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutUserCoinsInput
  connect?: Prisma.CoinWhereUniqueInput
}

export type CoinUpdateOneRequiredWithoutUserCoinsNestedInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutUserCoinsInput, Prisma.CoinUncheckedCreateWithoutUserCoinsInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutUserCoinsInput
  upsert?: Prisma.CoinUpsertWithoutUserCoinsInput
  connect?: Prisma.CoinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CoinUpdateToOneWithWhereWithoutUserCoinsInput, Prisma.CoinUpdateWithoutUserCoinsInput>, Prisma.CoinUncheckedUpdateWithoutUserCoinsInput>
}

export type CoinCreateNestedOneWithoutStrategiesInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutStrategiesInput, Prisma.CoinUncheckedCreateWithoutStrategiesInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutStrategiesInput
  connect?: Prisma.CoinWhereUniqueInput
}

export type CoinUpdateOneWithoutStrategiesNestedInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutStrategiesInput, Prisma.CoinUncheckedCreateWithoutStrategiesInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutStrategiesInput
  upsert?: Prisma.CoinUpsertWithoutStrategiesInput
  disconnect?: Prisma.CoinWhereInput | boolean
  delete?: Prisma.CoinWhereInput | boolean
  connect?: Prisma.CoinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CoinUpdateToOneWithWhereWithoutStrategiesInput, Prisma.CoinUpdateWithoutStrategiesInput>, Prisma.CoinUncheckedUpdateWithoutStrategiesInput>
}

export type CoinCreateNestedOneWithoutTradesInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutTradesInput, Prisma.CoinUncheckedCreateWithoutTradesInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutTradesInput
  connect?: Prisma.CoinWhereUniqueInput
}

export type CoinUpdateOneRequiredWithoutTradesNestedInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutTradesInput, Prisma.CoinUncheckedCreateWithoutTradesInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutTradesInput
  upsert?: Prisma.CoinUpsertWithoutTradesInput
  connect?: Prisma.CoinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CoinUpdateToOneWithWhereWithoutTradesInput, Prisma.CoinUpdateWithoutTradesInput>, Prisma.CoinUncheckedUpdateWithoutTradesInput>
}

export type CoinCreateNestedOneWithoutBalancesInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutBalancesInput, Prisma.CoinUncheckedCreateWithoutBalancesInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutBalancesInput
  connect?: Prisma.CoinWhereUniqueInput
}

export type CoinUpdateOneRequiredWithoutBalancesNestedInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutBalancesInput, Prisma.CoinUncheckedCreateWithoutBalancesInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutBalancesInput
  upsert?: Prisma.CoinUpsertWithoutBalancesInput
  connect?: Prisma.CoinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CoinUpdateToOneWithWhereWithoutBalancesInput, Prisma.CoinUpdateWithoutBalancesInput>, Prisma.CoinUncheckedUpdateWithoutBalancesInput>
}

export type CoinCreateNestedOneWithoutPortfolioHistoryInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutPortfolioHistoryInput, Prisma.CoinUncheckedCreateWithoutPortfolioHistoryInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutPortfolioHistoryInput
  connect?: Prisma.CoinWhereUniqueInput
}

export type CoinUpdateOneRequiredWithoutPortfolioHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutPortfolioHistoryInput, Prisma.CoinUncheckedCreateWithoutPortfolioHistoryInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutPortfolioHistoryInput
  upsert?: Prisma.CoinUpsertWithoutPortfolioHistoryInput
  connect?: Prisma.CoinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CoinUpdateToOneWithWhereWithoutPortfolioHistoryInput, Prisma.CoinUpdateWithoutPortfolioHistoryInput>, Prisma.CoinUncheckedUpdateWithoutPortfolioHistoryInput>
}

export type CoinCreateNestedOneWithoutWalletTradesFromInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesFromInput, Prisma.CoinUncheckedCreateWithoutWalletTradesFromInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutWalletTradesFromInput
  connect?: Prisma.CoinWhereUniqueInput
}

export type CoinCreateNestedOneWithoutWalletTradesToInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesToInput, Prisma.CoinUncheckedCreateWithoutWalletTradesToInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutWalletTradesToInput
  connect?: Prisma.CoinWhereUniqueInput
}

export type CoinUpdateOneRequiredWithoutWalletTradesFromNestedInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesFromInput, Prisma.CoinUncheckedCreateWithoutWalletTradesFromInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutWalletTradesFromInput
  upsert?: Prisma.CoinUpsertWithoutWalletTradesFromInput
  connect?: Prisma.CoinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CoinUpdateToOneWithWhereWithoutWalletTradesFromInput, Prisma.CoinUpdateWithoutWalletTradesFromInput>, Prisma.CoinUncheckedUpdateWithoutWalletTradesFromInput>
}

export type CoinUpdateOneRequiredWithoutWalletTradesToNestedInput = {
  create?: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesToInput, Prisma.CoinUncheckedCreateWithoutWalletTradesToInput>
  connectOrCreate?: Prisma.CoinCreateOrConnectWithoutWalletTradesToInput
  upsert?: Prisma.CoinUpsertWithoutWalletTradesToInput
  connect?: Prisma.CoinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CoinUpdateToOneWithWhereWithoutWalletTradesToInput, Prisma.CoinUpdateWithoutWalletTradesToInput>, Prisma.CoinUncheckedUpdateWithoutWalletTradesToInput>
}

export type CoinCreateWithoutUserCoinsInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeCreateNestedManyWithoutToCoinInput
}

export type CoinUncheckedCreateWithoutUserCoinsInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceUncheckedCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyUncheckedCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutToCoinInput
}

export type CoinCreateOrConnectWithoutUserCoinsInput = {
  where: Prisma.CoinWhereUniqueInput
  create: Prisma.XOR<Prisma.CoinCreateWithoutUserCoinsInput, Prisma.CoinUncheckedCreateWithoutUserCoinsInput>
}

export type CoinUpsertWithoutUserCoinsInput = {
  update: Prisma.XOR<Prisma.CoinUpdateWithoutUserCoinsInput, Prisma.CoinUncheckedUpdateWithoutUserCoinsInput>
  create: Prisma.XOR<Prisma.CoinCreateWithoutUserCoinsInput, Prisma.CoinUncheckedCreateWithoutUserCoinsInput>
  where?: Prisma.CoinWhereInput
}

export type CoinUpdateToOneWithWhereWithoutUserCoinsInput = {
  where?: Prisma.CoinWhereInput
  data: Prisma.XOR<Prisma.CoinUpdateWithoutUserCoinsInput, Prisma.CoinUncheckedUpdateWithoutUserCoinsInput>
}

export type CoinUpdateWithoutUserCoinsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUpdateManyWithoutToCoinNestedInput
}

export type CoinUncheckedUpdateWithoutUserCoinsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUncheckedUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUncheckedUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUncheckedUpdateManyWithoutToCoinNestedInput
}

export type CoinCreateWithoutStrategiesInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeCreateNestedManyWithoutToCoinInput
}

export type CoinUncheckedCreateWithoutStrategiesInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceUncheckedCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinUncheckedCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutToCoinInput
}

export type CoinCreateOrConnectWithoutStrategiesInput = {
  where: Prisma.CoinWhereUniqueInput
  create: Prisma.XOR<Prisma.CoinCreateWithoutStrategiesInput, Prisma.CoinUncheckedCreateWithoutStrategiesInput>
}

export type CoinUpsertWithoutStrategiesInput = {
  update: Prisma.XOR<Prisma.CoinUpdateWithoutStrategiesInput, Prisma.CoinUncheckedUpdateWithoutStrategiesInput>
  create: Prisma.XOR<Prisma.CoinCreateWithoutStrategiesInput, Prisma.CoinUncheckedCreateWithoutStrategiesInput>
  where?: Prisma.CoinWhereInput
}

export type CoinUpdateToOneWithWhereWithoutStrategiesInput = {
  where?: Prisma.CoinWhereInput
  data: Prisma.XOR<Prisma.CoinUpdateWithoutStrategiesInput, Prisma.CoinUncheckedUpdateWithoutStrategiesInput>
}

export type CoinUpdateWithoutStrategiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUpdateManyWithoutToCoinNestedInput
}

export type CoinUncheckedUpdateWithoutStrategiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUncheckedUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUncheckedUpdateManyWithoutToCoinNestedInput
}

export type CoinCreateWithoutTradesInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeCreateNestedManyWithoutToCoinInput
}

export type CoinUncheckedCreateWithoutTradesInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceUncheckedCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyUncheckedCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinUncheckedCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutToCoinInput
}

export type CoinCreateOrConnectWithoutTradesInput = {
  where: Prisma.CoinWhereUniqueInput
  create: Prisma.XOR<Prisma.CoinCreateWithoutTradesInput, Prisma.CoinUncheckedCreateWithoutTradesInput>
}

export type CoinUpsertWithoutTradesInput = {
  update: Prisma.XOR<Prisma.CoinUpdateWithoutTradesInput, Prisma.CoinUncheckedUpdateWithoutTradesInput>
  create: Prisma.XOR<Prisma.CoinCreateWithoutTradesInput, Prisma.CoinUncheckedCreateWithoutTradesInput>
  where?: Prisma.CoinWhereInput
}

export type CoinUpdateToOneWithWhereWithoutTradesInput = {
  where?: Prisma.CoinWhereInput
  data: Prisma.XOR<Prisma.CoinUpdateWithoutTradesInput, Prisma.CoinUncheckedUpdateWithoutTradesInput>
}

export type CoinUpdateWithoutTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUpdateManyWithoutToCoinNestedInput
}

export type CoinUncheckedUpdateWithoutTradesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUncheckedUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUncheckedUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUncheckedUpdateManyWithoutToCoinNestedInput
}

export type CoinCreateWithoutBalancesInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  portfolioHistory?: Prisma.PortfolioHistoryCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeCreateNestedManyWithoutToCoinInput
}

export type CoinUncheckedCreateWithoutBalancesInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyUncheckedCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinUncheckedCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutToCoinInput
}

export type CoinCreateOrConnectWithoutBalancesInput = {
  where: Prisma.CoinWhereUniqueInput
  create: Prisma.XOR<Prisma.CoinCreateWithoutBalancesInput, Prisma.CoinUncheckedCreateWithoutBalancesInput>
}

export type CoinUpsertWithoutBalancesInput = {
  update: Prisma.XOR<Prisma.CoinUpdateWithoutBalancesInput, Prisma.CoinUncheckedUpdateWithoutBalancesInput>
  create: Prisma.XOR<Prisma.CoinCreateWithoutBalancesInput, Prisma.CoinUncheckedCreateWithoutBalancesInput>
  where?: Prisma.CoinWhereInput
}

export type CoinUpdateToOneWithWhereWithoutBalancesInput = {
  where?: Prisma.CoinWhereInput
  data: Prisma.XOR<Prisma.CoinUpdateWithoutBalancesInput, Prisma.CoinUncheckedUpdateWithoutBalancesInput>
}

export type CoinUpdateWithoutBalancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portfolioHistory?: Prisma.PortfolioHistoryUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUpdateManyWithoutToCoinNestedInput
}

export type CoinUncheckedUpdateWithoutBalancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUncheckedUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUncheckedUpdateManyWithoutToCoinNestedInput
}

export type CoinCreateWithoutPortfolioHistoryInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeCreateNestedManyWithoutToCoinInput
}

export type CoinUncheckedCreateWithoutPortfolioHistoryInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceUncheckedCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyUncheckedCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinUncheckedCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutFromCoinInput
  walletTradesTo?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutToCoinInput
}

export type CoinCreateOrConnectWithoutPortfolioHistoryInput = {
  where: Prisma.CoinWhereUniqueInput
  create: Prisma.XOR<Prisma.CoinCreateWithoutPortfolioHistoryInput, Prisma.CoinUncheckedCreateWithoutPortfolioHistoryInput>
}

export type CoinUpsertWithoutPortfolioHistoryInput = {
  update: Prisma.XOR<Prisma.CoinUpdateWithoutPortfolioHistoryInput, Prisma.CoinUncheckedUpdateWithoutPortfolioHistoryInput>
  create: Prisma.XOR<Prisma.CoinCreateWithoutPortfolioHistoryInput, Prisma.CoinUncheckedCreateWithoutPortfolioHistoryInput>
  where?: Prisma.CoinWhereInput
}

export type CoinUpdateToOneWithWhereWithoutPortfolioHistoryInput = {
  where?: Prisma.CoinWhereInput
  data: Prisma.XOR<Prisma.CoinUpdateWithoutPortfolioHistoryInput, Prisma.CoinUncheckedUpdateWithoutPortfolioHistoryInput>
}

export type CoinUpdateWithoutPortfolioHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUpdateManyWithoutToCoinNestedInput
}

export type CoinUncheckedUpdateWithoutPortfolioHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUncheckedUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUncheckedUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedUpdateManyWithoutFromCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUncheckedUpdateManyWithoutToCoinNestedInput
}

export type CoinCreateWithoutWalletTradesFromInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinCreateNestedManyWithoutCoinInput
  walletTradesTo?: Prisma.WalletTradeCreateNestedManyWithoutToCoinInput
}

export type CoinUncheckedCreateWithoutWalletTradesFromInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceUncheckedCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyUncheckedCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinUncheckedCreateNestedManyWithoutCoinInput
  walletTradesTo?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutToCoinInput
}

export type CoinCreateOrConnectWithoutWalletTradesFromInput = {
  where: Prisma.CoinWhereUniqueInput
  create: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesFromInput, Prisma.CoinUncheckedCreateWithoutWalletTradesFromInput>
}

export type CoinCreateWithoutWalletTradesToInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeCreateNestedManyWithoutFromCoinInput
}

export type CoinUncheckedCreateWithoutWalletTradesToInput = {
  id: string
  name: string
  symbol: string
  image?: string | null
  balances?: Prisma.BalanceUncheckedCreateNestedManyWithoutCoinInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput
  strategies?: Prisma.StrategyUncheckedCreateNestedManyWithoutCoinInput
  trades?: Prisma.TradeUncheckedCreateNestedManyWithoutCoinInput
  userCoins?: Prisma.UserCoinUncheckedCreateNestedManyWithoutCoinInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedCreateNestedManyWithoutFromCoinInput
}

export type CoinCreateOrConnectWithoutWalletTradesToInput = {
  where: Prisma.CoinWhereUniqueInput
  create: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesToInput, Prisma.CoinUncheckedCreateWithoutWalletTradesToInput>
}

export type CoinUpsertWithoutWalletTradesFromInput = {
  update: Prisma.XOR<Prisma.CoinUpdateWithoutWalletTradesFromInput, Prisma.CoinUncheckedUpdateWithoutWalletTradesFromInput>
  create: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesFromInput, Prisma.CoinUncheckedCreateWithoutWalletTradesFromInput>
  where?: Prisma.CoinWhereInput
}

export type CoinUpdateToOneWithWhereWithoutWalletTradesFromInput = {
  where?: Prisma.CoinWhereInput
  data: Prisma.XOR<Prisma.CoinUpdateWithoutWalletTradesFromInput, Prisma.CoinUncheckedUpdateWithoutWalletTradesFromInput>
}

export type CoinUpdateWithoutWalletTradesFromInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUpdateManyWithoutCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUpdateManyWithoutToCoinNestedInput
}

export type CoinUncheckedUpdateWithoutWalletTradesFromInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUncheckedUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUncheckedUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesTo?: Prisma.WalletTradeUncheckedUpdateManyWithoutToCoinNestedInput
}

export type CoinUpsertWithoutWalletTradesToInput = {
  update: Prisma.XOR<Prisma.CoinUpdateWithoutWalletTradesToInput, Prisma.CoinUncheckedUpdateWithoutWalletTradesToInput>
  create: Prisma.XOR<Prisma.CoinCreateWithoutWalletTradesToInput, Prisma.CoinUncheckedCreateWithoutWalletTradesToInput>
  where?: Prisma.CoinWhereInput
}

export type CoinUpdateToOneWithWhereWithoutWalletTradesToInput = {
  where?: Prisma.CoinWhereInput
  data: Prisma.XOR<Prisma.CoinUpdateWithoutWalletTradesToInput, Prisma.CoinUncheckedUpdateWithoutWalletTradesToInput>
}

export type CoinUpdateWithoutWalletTradesToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUpdateManyWithoutFromCoinNestedInput
}

export type CoinUncheckedUpdateWithoutWalletTradesToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balances?: Prisma.BalanceUncheckedUpdateManyWithoutCoinNestedInput
  portfolioHistory?: Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput
  strategies?: Prisma.StrategyUncheckedUpdateManyWithoutCoinNestedInput
  trades?: Prisma.TradeUncheckedUpdateManyWithoutCoinNestedInput
  userCoins?: Prisma.UserCoinUncheckedUpdateManyWithoutCoinNestedInput
  walletTradesFrom?: Prisma.WalletTradeUncheckedUpdateManyWithoutFromCoinNestedInput
}


/**
 * Count Type CoinCountOutputType
 */

export type CoinCountOutputType = {
  balances: number
  portfolioHistory: number
  strategies: number
  trades: number
  userCoins: number
  walletTradesFrom: number
  walletTradesTo: number
}

export type CoinCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  balances?: boolean | CoinCountOutputTypeCountBalancesArgs
  portfolioHistory?: boolean | CoinCountOutputTypeCountPortfolioHistoryArgs
  strategies?: boolean | CoinCountOutputTypeCountStrategiesArgs
  trades?: boolean | CoinCountOutputTypeCountTradesArgs
  userCoins?: boolean | CoinCountOutputTypeCountUserCoinsArgs
  walletTradesFrom?: boolean | CoinCountOutputTypeCountWalletTradesFromArgs
  walletTradesTo?: boolean | CoinCountOutputTypeCountWalletTradesToArgs
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinCountOutputType
   */
  select?: Prisma.CoinCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeCountBalancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BalanceWhereInput
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeCountPortfolioHistoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PortfolioHistoryWhereInput
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeCountStrategiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StrategyWhereInput
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeCountTradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TradeWhereInput
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeCountUserCoinsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserCoinWhereInput
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeCountWalletTradesFromArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WalletTradeWhereInput
}

/**
 * CoinCountOutputType without action
 */
export type CoinCountOutputTypeCountWalletTradesToArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WalletTradeWhereInput
}


export type CoinSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  symbol?: boolean
  image?: boolean
  balances?: boolean | Prisma.Coin$balancesArgs<ExtArgs>
  portfolioHistory?: boolean | Prisma.Coin$portfolioHistoryArgs<ExtArgs>
  strategies?: boolean | Prisma.Coin$strategiesArgs<ExtArgs>
  trades?: boolean | Prisma.Coin$tradesArgs<ExtArgs>
  userCoins?: boolean | Prisma.Coin$userCoinsArgs<ExtArgs>
  walletTradesFrom?: boolean | Prisma.Coin$walletTradesFromArgs<ExtArgs>
  walletTradesTo?: boolean | Prisma.Coin$walletTradesToArgs<ExtArgs>
  _count?: boolean | Prisma.CoinCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["coin"]>

export type CoinSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  symbol?: boolean
  image?: boolean
}, ExtArgs["result"]["coin"]>

export type CoinSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  symbol?: boolean
  image?: boolean
}, ExtArgs["result"]["coin"]>

export type CoinSelectScalar = {
  id?: boolean
  name?: boolean
  symbol?: boolean
  image?: boolean
}

export type CoinOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "symbol" | "image", ExtArgs["result"]["coin"]>
export type CoinInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  balances?: boolean | Prisma.Coin$balancesArgs<ExtArgs>
  portfolioHistory?: boolean | Prisma.Coin$portfolioHistoryArgs<ExtArgs>
  strategies?: boolean | Prisma.Coin$strategiesArgs<ExtArgs>
  trades?: boolean | Prisma.Coin$tradesArgs<ExtArgs>
  userCoins?: boolean | Prisma.Coin$userCoinsArgs<ExtArgs>
  walletTradesFrom?: boolean | Prisma.Coin$walletTradesFromArgs<ExtArgs>
  walletTradesTo?: boolean | Prisma.Coin$walletTradesToArgs<ExtArgs>
  _count?: boolean | Prisma.CoinCountOutputTypeDefaultArgs<ExtArgs>
}
export type CoinIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CoinIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CoinPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Coin"
  objects: {
    balances: Prisma.$BalancePayload<ExtArgs>[]
    portfolioHistory: Prisma.$PortfolioHistoryPayload<ExtArgs>[]
    strategies: Prisma.$StrategyPayload<ExtArgs>[]
    trades: Prisma.$TradePayload<ExtArgs>[]
    userCoins: Prisma.$UserCoinPayload<ExtArgs>[]
    walletTradesFrom: Prisma.$WalletTradePayload<ExtArgs>[]
    walletTradesTo: Prisma.$WalletTradePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    symbol: string
    image: string | null
  }, ExtArgs["result"]["coin"]>
  composites: {}
}

export type CoinGetPayload<S extends boolean | null | undefined | CoinDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CoinPayload, S>

export type CoinCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CoinFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CoinCountAggregateInputType | true
  }

export interface CoinDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Coin'], meta: { name: 'Coin' } }
  /**
   * Find zero or one Coin that matches the filter.
   * @param {CoinFindUniqueArgs} args - Arguments to find a Coin
   * @example
   * // Get one Coin
   * const coin = await prisma.coin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CoinFindUniqueArgs>(args: Prisma.SelectSubset<T, CoinFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Coin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CoinFindUniqueOrThrowArgs} args - Arguments to find a Coin
   * @example
   * // Get one Coin
   * const coin = await prisma.coin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CoinFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CoinFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Coin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinFindFirstArgs} args - Arguments to find a Coin
   * @example
   * // Get one Coin
   * const coin = await prisma.coin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CoinFindFirstArgs>(args?: Prisma.SelectSubset<T, CoinFindFirstArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Coin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinFindFirstOrThrowArgs} args - Arguments to find a Coin
   * @example
   * // Get one Coin
   * const coin = await prisma.coin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CoinFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CoinFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Coins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Coins
   * const coins = await prisma.coin.findMany()
   * 
   * // Get first 10 Coins
   * const coins = await prisma.coin.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const coinWithIdOnly = await prisma.coin.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CoinFindManyArgs>(args?: Prisma.SelectSubset<T, CoinFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Coin.
   * @param {CoinCreateArgs} args - Arguments to create a Coin.
   * @example
   * // Create one Coin
   * const Coin = await prisma.coin.create({
   *   data: {
   *     // ... data to create a Coin
   *   }
   * })
   * 
   */
  create<T extends CoinCreateArgs>(args: Prisma.SelectSubset<T, CoinCreateArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Coins.
   * @param {CoinCreateManyArgs} args - Arguments to create many Coins.
   * @example
   * // Create many Coins
   * const coin = await prisma.coin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CoinCreateManyArgs>(args?: Prisma.SelectSubset<T, CoinCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Coins and returns the data saved in the database.
   * @param {CoinCreateManyAndReturnArgs} args - Arguments to create many Coins.
   * @example
   * // Create many Coins
   * const coin = await prisma.coin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Coins and only return the `id`
   * const coinWithIdOnly = await prisma.coin.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CoinCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CoinCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Coin.
   * @param {CoinDeleteArgs} args - Arguments to delete one Coin.
   * @example
   * // Delete one Coin
   * const Coin = await prisma.coin.delete({
   *   where: {
   *     // ... filter to delete one Coin
   *   }
   * })
   * 
   */
  delete<T extends CoinDeleteArgs>(args: Prisma.SelectSubset<T, CoinDeleteArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Coin.
   * @param {CoinUpdateArgs} args - Arguments to update one Coin.
   * @example
   * // Update one Coin
   * const coin = await prisma.coin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CoinUpdateArgs>(args: Prisma.SelectSubset<T, CoinUpdateArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Coins.
   * @param {CoinDeleteManyArgs} args - Arguments to filter Coins to delete.
   * @example
   * // Delete a few Coins
   * const { count } = await prisma.coin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CoinDeleteManyArgs>(args?: Prisma.SelectSubset<T, CoinDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Coins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Coins
   * const coin = await prisma.coin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CoinUpdateManyArgs>(args: Prisma.SelectSubset<T, CoinUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Coins and returns the data updated in the database.
   * @param {CoinUpdateManyAndReturnArgs} args - Arguments to update many Coins.
   * @example
   * // Update many Coins
   * const coin = await prisma.coin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Coins and only return the `id`
   * const coinWithIdOnly = await prisma.coin.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CoinUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CoinUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Coin.
   * @param {CoinUpsertArgs} args - Arguments to update or create a Coin.
   * @example
   * // Update or create a Coin
   * const coin = await prisma.coin.upsert({
   *   create: {
   *     // ... data to create a Coin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Coin we want to update
   *   }
   * })
   */
  upsert<T extends CoinUpsertArgs>(args: Prisma.SelectSubset<T, CoinUpsertArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Coins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinCountArgs} args - Arguments to filter Coins to count.
   * @example
   * // Count the number of Coins
   * const count = await prisma.coin.count({
   *   where: {
   *     // ... the filter for the Coins we want to count
   *   }
   * })
  **/
  count<T extends CoinCountArgs>(
    args?: Prisma.Subset<T, CoinCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CoinCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Coin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CoinAggregateArgs>(args: Prisma.Subset<T, CoinAggregateArgs>): Prisma.PrismaPromise<GetCoinAggregateType<T>>

  /**
   * Group by Coin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CoinGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CoinGroupByArgs['orderBy'] }
      : { orderBy?: CoinGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CoinGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCoinGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Coin model
 */
readonly fields: CoinFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Coin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CoinClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  balances<T extends Prisma.Coin$balancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Coin$balancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BalancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  portfolioHistory<T extends Prisma.Coin$portfolioHistoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Coin$portfolioHistoryArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  strategies<T extends Prisma.Coin$strategiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Coin$strategiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StrategyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  trades<T extends Prisma.Coin$tradesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Coin$tradesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  userCoins<T extends Prisma.Coin$userCoinsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Coin$userCoinsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  walletTradesFrom<T extends Prisma.Coin$walletTradesFromArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Coin$walletTradesFromArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WalletTradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  walletTradesTo<T extends Prisma.Coin$walletTradesToArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Coin$walletTradesToArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WalletTradePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Coin model
 */
export interface CoinFieldRefs {
  readonly id: Prisma.FieldRef<"Coin", 'String'>
  readonly name: Prisma.FieldRef<"Coin", 'String'>
  readonly symbol: Prisma.FieldRef<"Coin", 'String'>
  readonly image: Prisma.FieldRef<"Coin", 'String'>
}
    

// Custom InputTypes
/**
 * Coin findUnique
 */
export type CoinFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * Filter, which Coin to fetch.
   */
  where: Prisma.CoinWhereUniqueInput
}

/**
 * Coin findUniqueOrThrow
 */
export type CoinFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * Filter, which Coin to fetch.
   */
  where: Prisma.CoinWhereUniqueInput
}

/**
 * Coin findFirst
 */
export type CoinFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * Filter, which Coin to fetch.
   */
  where?: Prisma.CoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Coins to fetch.
   */
  orderBy?: Prisma.CoinOrderByWithRelationInput | Prisma.CoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Coins.
   */
  cursor?: Prisma.CoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Coins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Coins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Coins.
   */
  distinct?: Prisma.CoinScalarFieldEnum | Prisma.CoinScalarFieldEnum[]
}

/**
 * Coin findFirstOrThrow
 */
export type CoinFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * Filter, which Coin to fetch.
   */
  where?: Prisma.CoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Coins to fetch.
   */
  orderBy?: Prisma.CoinOrderByWithRelationInput | Prisma.CoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Coins.
   */
  cursor?: Prisma.CoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Coins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Coins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Coins.
   */
  distinct?: Prisma.CoinScalarFieldEnum | Prisma.CoinScalarFieldEnum[]
}

/**
 * Coin findMany
 */
export type CoinFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * Filter, which Coins to fetch.
   */
  where?: Prisma.CoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Coins to fetch.
   */
  orderBy?: Prisma.CoinOrderByWithRelationInput | Prisma.CoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Coins.
   */
  cursor?: Prisma.CoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Coins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Coins.
   */
  skip?: number
  distinct?: Prisma.CoinScalarFieldEnum | Prisma.CoinScalarFieldEnum[]
}

/**
 * Coin create
 */
export type CoinCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * The data needed to create a Coin.
   */
  data: Prisma.XOR<Prisma.CoinCreateInput, Prisma.CoinUncheckedCreateInput>
}

/**
 * Coin createMany
 */
export type CoinCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Coins.
   */
  data: Prisma.CoinCreateManyInput | Prisma.CoinCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Coin createManyAndReturn
 */
export type CoinCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * The data used to create many Coins.
   */
  data: Prisma.CoinCreateManyInput | Prisma.CoinCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Coin update
 */
export type CoinUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * The data needed to update a Coin.
   */
  data: Prisma.XOR<Prisma.CoinUpdateInput, Prisma.CoinUncheckedUpdateInput>
  /**
   * Choose, which Coin to update.
   */
  where: Prisma.CoinWhereUniqueInput
}

/**
 * Coin updateMany
 */
export type CoinUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Coins.
   */
  data: Prisma.XOR<Prisma.CoinUpdateManyMutationInput, Prisma.CoinUncheckedUpdateManyInput>
  /**
   * Filter which Coins to update
   */
  where?: Prisma.CoinWhereInput
  /**
   * Limit how many Coins to update.
   */
  limit?: number
}

/**
 * Coin updateManyAndReturn
 */
export type CoinUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * The data used to update Coins.
   */
  data: Prisma.XOR<Prisma.CoinUpdateManyMutationInput, Prisma.CoinUncheckedUpdateManyInput>
  /**
   * Filter which Coins to update
   */
  where?: Prisma.CoinWhereInput
  /**
   * Limit how many Coins to update.
   */
  limit?: number
}

/**
 * Coin upsert
 */
export type CoinUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * The filter to search for the Coin to update in case it exists.
   */
  where: Prisma.CoinWhereUniqueInput
  /**
   * In case the Coin found by the `where` argument doesn't exist, create a new Coin with this data.
   */
  create: Prisma.XOR<Prisma.CoinCreateInput, Prisma.CoinUncheckedCreateInput>
  /**
   * In case the Coin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CoinUpdateInput, Prisma.CoinUncheckedUpdateInput>
}

/**
 * Coin delete
 */
export type CoinDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
  /**
   * Filter which Coin to delete.
   */
  where: Prisma.CoinWhereUniqueInput
}

/**
 * Coin deleteMany
 */
export type CoinDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Coins to delete
   */
  where?: Prisma.CoinWhereInput
  /**
   * Limit how many Coins to delete.
   */
  limit?: number
}

/**
 * Coin.balances
 */
export type Coin$balancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Balance
   */
  select?: Prisma.BalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Balance
   */
  omit?: Prisma.BalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BalanceInclude<ExtArgs> | null
  where?: Prisma.BalanceWhereInput
  orderBy?: Prisma.BalanceOrderByWithRelationInput | Prisma.BalanceOrderByWithRelationInput[]
  cursor?: Prisma.BalanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BalanceScalarFieldEnum | Prisma.BalanceScalarFieldEnum[]
}

/**
 * Coin.portfolioHistory
 */
export type Coin$portfolioHistoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  where?: Prisma.PortfolioHistoryWhereInput
  orderBy?: Prisma.PortfolioHistoryOrderByWithRelationInput | Prisma.PortfolioHistoryOrderByWithRelationInput[]
  cursor?: Prisma.PortfolioHistoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PortfolioHistoryScalarFieldEnum | Prisma.PortfolioHistoryScalarFieldEnum[]
}

/**
 * Coin.strategies
 */
export type Coin$strategiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Strategy
   */
  select?: Prisma.StrategySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Strategy
   */
  omit?: Prisma.StrategyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StrategyInclude<ExtArgs> | null
  where?: Prisma.StrategyWhereInput
  orderBy?: Prisma.StrategyOrderByWithRelationInput | Prisma.StrategyOrderByWithRelationInput[]
  cursor?: Prisma.StrategyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StrategyScalarFieldEnum | Prisma.StrategyScalarFieldEnum[]
}

/**
 * Coin.trades
 */
export type Coin$tradesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trade
   */
  select?: Prisma.TradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trade
   */
  omit?: Prisma.TradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeInclude<ExtArgs> | null
  where?: Prisma.TradeWhereInput
  orderBy?: Prisma.TradeOrderByWithRelationInput | Prisma.TradeOrderByWithRelationInput[]
  cursor?: Prisma.TradeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TradeScalarFieldEnum | Prisma.TradeScalarFieldEnum[]
}

/**
 * Coin.userCoins
 */
export type Coin$userCoinsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  where?: Prisma.UserCoinWhereInput
  orderBy?: Prisma.UserCoinOrderByWithRelationInput | Prisma.UserCoinOrderByWithRelationInput[]
  cursor?: Prisma.UserCoinWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserCoinScalarFieldEnum | Prisma.UserCoinScalarFieldEnum[]
}

/**
 * Coin.walletTradesFrom
 */
export type Coin$walletTradesFromArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WalletTrade
   */
  select?: Prisma.WalletTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WalletTrade
   */
  omit?: Prisma.WalletTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WalletTradeInclude<ExtArgs> | null
  where?: Prisma.WalletTradeWhereInput
  orderBy?: Prisma.WalletTradeOrderByWithRelationInput | Prisma.WalletTradeOrderByWithRelationInput[]
  cursor?: Prisma.WalletTradeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WalletTradeScalarFieldEnum | Prisma.WalletTradeScalarFieldEnum[]
}

/**
 * Coin.walletTradesTo
 */
export type Coin$walletTradesToArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WalletTrade
   */
  select?: Prisma.WalletTradeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WalletTrade
   */
  omit?: Prisma.WalletTradeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WalletTradeInclude<ExtArgs> | null
  where?: Prisma.WalletTradeWhereInput
  orderBy?: Prisma.WalletTradeOrderByWithRelationInput | Prisma.WalletTradeOrderByWithRelationInput[]
  cursor?: Prisma.WalletTradeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WalletTradeScalarFieldEnum | Prisma.WalletTradeScalarFieldEnum[]
}

/**
 * Coin without action
 */
export type CoinDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Coin
   */
  select?: Prisma.CoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Coin
   */
  omit?: Prisma.CoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoinInclude<ExtArgs> | null
}
