
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PortfolioHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PortfolioHistory
 * 
 */
export type PortfolioHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$PortfolioHistoryPayload>

export type AggregatePortfolioHistory = {
  _count: PortfolioHistoryCountAggregateOutputType | null
  _avg: PortfolioHistoryAvgAggregateOutputType | null
  _sum: PortfolioHistorySumAggregateOutputType | null
  _min: PortfolioHistoryMinAggregateOutputType | null
  _max: PortfolioHistoryMaxAggregateOutputType | null
}

export type PortfolioHistoryAvgAggregateOutputType = {
  usdValue: number | null
}

export type PortfolioHistorySumAggregateOutputType = {
  usdValue: number | null
}

export type PortfolioHistoryMinAggregateOutputType = {
  id: string | null
  userId: string | null
  coinId: string | null
  date: Date | null
  usdValue: number | null
}

export type PortfolioHistoryMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  coinId: string | null
  date: Date | null
  usdValue: number | null
}

export type PortfolioHistoryCountAggregateOutputType = {
  id: number
  userId: number
  coinId: number
  date: number
  usdValue: number
  _all: number
}


export type PortfolioHistoryAvgAggregateInputType = {
  usdValue?: true
}

export type PortfolioHistorySumAggregateInputType = {
  usdValue?: true
}

export type PortfolioHistoryMinAggregateInputType = {
  id?: true
  userId?: true
  coinId?: true
  date?: true
  usdValue?: true
}

export type PortfolioHistoryMaxAggregateInputType = {
  id?: true
  userId?: true
  coinId?: true
  date?: true
  usdValue?: true
}

export type PortfolioHistoryCountAggregateInputType = {
  id?: true
  userId?: true
  coinId?: true
  date?: true
  usdValue?: true
  _all?: true
}

export type PortfolioHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PortfolioHistory to aggregate.
   */
  where?: Prisma.PortfolioHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PortfolioHistories to fetch.
   */
  orderBy?: Prisma.PortfolioHistoryOrderByWithRelationInput | Prisma.PortfolioHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PortfolioHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PortfolioHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PortfolioHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PortfolioHistories
  **/
  _count?: true | PortfolioHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PortfolioHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PortfolioHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PortfolioHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PortfolioHistoryMaxAggregateInputType
}

export type GetPortfolioHistoryAggregateType<T extends PortfolioHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregatePortfolioHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePortfolioHistory[P]>
    : Prisma.GetScalarType<T[P], AggregatePortfolioHistory[P]>
}




export type PortfolioHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PortfolioHistoryWhereInput
  orderBy?: Prisma.PortfolioHistoryOrderByWithAggregationInput | Prisma.PortfolioHistoryOrderByWithAggregationInput[]
  by: Prisma.PortfolioHistoryScalarFieldEnum[] | Prisma.PortfolioHistoryScalarFieldEnum
  having?: Prisma.PortfolioHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PortfolioHistoryCountAggregateInputType | true
  _avg?: PortfolioHistoryAvgAggregateInputType
  _sum?: PortfolioHistorySumAggregateInputType
  _min?: PortfolioHistoryMinAggregateInputType
  _max?: PortfolioHistoryMaxAggregateInputType
}

export type PortfolioHistoryGroupByOutputType = {
  id: string
  userId: string
  coinId: string
  date: Date
  usdValue: number
  _count: PortfolioHistoryCountAggregateOutputType | null
  _avg: PortfolioHistoryAvgAggregateOutputType | null
  _sum: PortfolioHistorySumAggregateOutputType | null
  _min: PortfolioHistoryMinAggregateOutputType | null
  _max: PortfolioHistoryMaxAggregateOutputType | null
}

type GetPortfolioHistoryGroupByPayload<T extends PortfolioHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PortfolioHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PortfolioHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PortfolioHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PortfolioHistoryGroupByOutputType[P]>
      }
    >
  >



export type PortfolioHistoryWhereInput = {
  AND?: Prisma.PortfolioHistoryWhereInput | Prisma.PortfolioHistoryWhereInput[]
  OR?: Prisma.PortfolioHistoryWhereInput[]
  NOT?: Prisma.PortfolioHistoryWhereInput | Prisma.PortfolioHistoryWhereInput[]
  id?: Prisma.StringFilter<"PortfolioHistory"> | string
  userId?: Prisma.StringFilter<"PortfolioHistory"> | string
  coinId?: Prisma.StringFilter<"PortfolioHistory"> | string
  date?: Prisma.DateTimeFilter<"PortfolioHistory"> | Date | string
  usdValue?: Prisma.FloatFilter<"PortfolioHistory"> | number
  coin?: Prisma.XOR<Prisma.CoinScalarRelationFilter, Prisma.CoinWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PortfolioHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  usdValue?: Prisma.SortOrder
  coin?: Prisma.CoinOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type PortfolioHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_coinId_date?: Prisma.PortfolioHistoryUserIdCoinIdDateCompoundUniqueInput
  AND?: Prisma.PortfolioHistoryWhereInput | Prisma.PortfolioHistoryWhereInput[]
  OR?: Prisma.PortfolioHistoryWhereInput[]
  NOT?: Prisma.PortfolioHistoryWhereInput | Prisma.PortfolioHistoryWhereInput[]
  userId?: Prisma.StringFilter<"PortfolioHistory"> | string
  coinId?: Prisma.StringFilter<"PortfolioHistory"> | string
  date?: Prisma.DateTimeFilter<"PortfolioHistory"> | Date | string
  usdValue?: Prisma.FloatFilter<"PortfolioHistory"> | number
  coin?: Prisma.XOR<Prisma.CoinScalarRelationFilter, Prisma.CoinWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_coinId_date">

export type PortfolioHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  usdValue?: Prisma.SortOrder
  _count?: Prisma.PortfolioHistoryCountOrderByAggregateInput
  _avg?: Prisma.PortfolioHistoryAvgOrderByAggregateInput
  _max?: Prisma.PortfolioHistoryMaxOrderByAggregateInput
  _min?: Prisma.PortfolioHistoryMinOrderByAggregateInput
  _sum?: Prisma.PortfolioHistorySumOrderByAggregateInput
}

export type PortfolioHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.PortfolioHistoryScalarWhereWithAggregatesInput | Prisma.PortfolioHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.PortfolioHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PortfolioHistoryScalarWhereWithAggregatesInput | Prisma.PortfolioHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PortfolioHistory"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PortfolioHistory"> | string
  coinId?: Prisma.StringWithAggregatesFilter<"PortfolioHistory"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"PortfolioHistory"> | Date | string
  usdValue?: Prisma.FloatWithAggregatesFilter<"PortfolioHistory"> | number
}

export type PortfolioHistoryCreateInput = {
  id?: string
  date?: Date | string
  usdValue: number
  coin: Prisma.CoinCreateNestedOneWithoutPortfolioHistoryInput
  user: Prisma.UserCreateNestedOneWithoutPortfolioHistoryInput
}

export type PortfolioHistoryUncheckedCreateInput = {
  id?: string
  userId: string
  coinId: string
  date?: Date | string
  usdValue: number
}

export type PortfolioHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
  coin?: Prisma.CoinUpdateOneRequiredWithoutPortfolioHistoryNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutPortfolioHistoryNestedInput
}

export type PortfolioHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PortfolioHistoryCreateManyInput = {
  id?: string
  userId: string
  coinId: string
  date?: Date | string
  usdValue: number
}

export type PortfolioHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PortfolioHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PortfolioHistoryListRelationFilter = {
  every?: Prisma.PortfolioHistoryWhereInput
  some?: Prisma.PortfolioHistoryWhereInput
  none?: Prisma.PortfolioHistoryWhereInput
}

export type PortfolioHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PortfolioHistoryUserIdCoinIdDateCompoundUniqueInput = {
  userId: string
  coinId: string
  date: Date | string
}

export type PortfolioHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  usdValue?: Prisma.SortOrder
}

export type PortfolioHistoryAvgOrderByAggregateInput = {
  usdValue?: Prisma.SortOrder
}

export type PortfolioHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  usdValue?: Prisma.SortOrder
}

export type PortfolioHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  usdValue?: Prisma.SortOrder
}

export type PortfolioHistorySumOrderByAggregateInput = {
  usdValue?: Prisma.SortOrder
}

export type PortfolioHistoryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutUserInput, Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput> | Prisma.PortfolioHistoryCreateWithoutUserInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput | Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyUserInputEnvelope
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
}

export type PortfolioHistoryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutUserInput, Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput> | Prisma.PortfolioHistoryCreateWithoutUserInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput | Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyUserInputEnvelope
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
}

export type PortfolioHistoryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutUserInput, Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput> | Prisma.PortfolioHistoryCreateWithoutUserInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput | Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyUserInputEnvelope
  set?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  disconnect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  delete?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  update?: Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PortfolioHistoryUpdateManyWithWhereWithoutUserInput | Prisma.PortfolioHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PortfolioHistoryScalarWhereInput | Prisma.PortfolioHistoryScalarWhereInput[]
}

export type PortfolioHistoryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutUserInput, Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput> | Prisma.PortfolioHistoryCreateWithoutUserInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput | Prisma.PortfolioHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyUserInputEnvelope
  set?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  disconnect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  delete?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  update?: Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PortfolioHistoryUpdateManyWithWhereWithoutUserInput | Prisma.PortfolioHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PortfolioHistoryScalarWhereInput | Prisma.PortfolioHistoryScalarWhereInput[]
}

export type PortfolioHistoryCreateNestedManyWithoutCoinInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput> | Prisma.PortfolioHistoryCreateWithoutCoinInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput | Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyCoinInputEnvelope
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
}

export type PortfolioHistoryUncheckedCreateNestedManyWithoutCoinInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput> | Prisma.PortfolioHistoryCreateWithoutCoinInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput | Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyCoinInputEnvelope
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
}

export type PortfolioHistoryUpdateManyWithoutCoinNestedInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput> | Prisma.PortfolioHistoryCreateWithoutCoinInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput | Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput[]
  upsert?: Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutCoinInput | Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutCoinInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyCoinInputEnvelope
  set?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  disconnect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  delete?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  update?: Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutCoinInput | Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutCoinInput[]
  updateMany?: Prisma.PortfolioHistoryUpdateManyWithWhereWithoutCoinInput | Prisma.PortfolioHistoryUpdateManyWithWhereWithoutCoinInput[]
  deleteMany?: Prisma.PortfolioHistoryScalarWhereInput | Prisma.PortfolioHistoryScalarWhereInput[]
}

export type PortfolioHistoryUncheckedUpdateManyWithoutCoinNestedInput = {
  create?: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput> | Prisma.PortfolioHistoryCreateWithoutCoinInput[] | Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput | Prisma.PortfolioHistoryCreateOrConnectWithoutCoinInput[]
  upsert?: Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutCoinInput | Prisma.PortfolioHistoryUpsertWithWhereUniqueWithoutCoinInput[]
  createMany?: Prisma.PortfolioHistoryCreateManyCoinInputEnvelope
  set?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  disconnect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  delete?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  connect?: Prisma.PortfolioHistoryWhereUniqueInput | Prisma.PortfolioHistoryWhereUniqueInput[]
  update?: Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutCoinInput | Prisma.PortfolioHistoryUpdateWithWhereUniqueWithoutCoinInput[]
  updateMany?: Prisma.PortfolioHistoryUpdateManyWithWhereWithoutCoinInput | Prisma.PortfolioHistoryUpdateManyWithWhereWithoutCoinInput[]
  deleteMany?: Prisma.PortfolioHistoryScalarWhereInput | Prisma.PortfolioHistoryScalarWhereInput[]
}

export type PortfolioHistoryCreateWithoutUserInput = {
  id?: string
  date?: Date | string
  usdValue: number
  coin: Prisma.CoinCreateNestedOneWithoutPortfolioHistoryInput
}

export type PortfolioHistoryUncheckedCreateWithoutUserInput = {
  id?: string
  coinId: string
  date?: Date | string
  usdValue: number
}

export type PortfolioHistoryCreateOrConnectWithoutUserInput = {
  where: Prisma.PortfolioHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutUserInput, Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput>
}

export type PortfolioHistoryCreateManyUserInputEnvelope = {
  data: Prisma.PortfolioHistoryCreateManyUserInput | Prisma.PortfolioHistoryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PortfolioHistoryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PortfolioHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.PortfolioHistoryUpdateWithoutUserInput, Prisma.PortfolioHistoryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutUserInput, Prisma.PortfolioHistoryUncheckedCreateWithoutUserInput>
}

export type PortfolioHistoryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PortfolioHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.PortfolioHistoryUpdateWithoutUserInput, Prisma.PortfolioHistoryUncheckedUpdateWithoutUserInput>
}

export type PortfolioHistoryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PortfolioHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.PortfolioHistoryUpdateManyMutationInput, Prisma.PortfolioHistoryUncheckedUpdateManyWithoutUserInput>
}

export type PortfolioHistoryScalarWhereInput = {
  AND?: Prisma.PortfolioHistoryScalarWhereInput | Prisma.PortfolioHistoryScalarWhereInput[]
  OR?: Prisma.PortfolioHistoryScalarWhereInput[]
  NOT?: Prisma.PortfolioHistoryScalarWhereInput | Prisma.PortfolioHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"PortfolioHistory"> | string
  userId?: Prisma.StringFilter<"PortfolioHistory"> | string
  coinId?: Prisma.StringFilter<"PortfolioHistory"> | string
  date?: Prisma.DateTimeFilter<"PortfolioHistory"> | Date | string
  usdValue?: Prisma.FloatFilter<"PortfolioHistory"> | number
}

export type PortfolioHistoryCreateWithoutCoinInput = {
  id?: string
  date?: Date | string
  usdValue: number
  user: Prisma.UserCreateNestedOneWithoutPortfolioHistoryInput
}

export type PortfolioHistoryUncheckedCreateWithoutCoinInput = {
  id?: string
  userId: string
  date?: Date | string
  usdValue: number
}

export type PortfolioHistoryCreateOrConnectWithoutCoinInput = {
  where: Prisma.PortfolioHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput>
}

export type PortfolioHistoryCreateManyCoinInputEnvelope = {
  data: Prisma.PortfolioHistoryCreateManyCoinInput | Prisma.PortfolioHistoryCreateManyCoinInput[]
  skipDuplicates?: boolean
}

export type PortfolioHistoryUpsertWithWhereUniqueWithoutCoinInput = {
  where: Prisma.PortfolioHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.PortfolioHistoryUpdateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedUpdateWithoutCoinInput>
  create: Prisma.XOR<Prisma.PortfolioHistoryCreateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedCreateWithoutCoinInput>
}

export type PortfolioHistoryUpdateWithWhereUniqueWithoutCoinInput = {
  where: Prisma.PortfolioHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.PortfolioHistoryUpdateWithoutCoinInput, Prisma.PortfolioHistoryUncheckedUpdateWithoutCoinInput>
}

export type PortfolioHistoryUpdateManyWithWhereWithoutCoinInput = {
  where: Prisma.PortfolioHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.PortfolioHistoryUpdateManyMutationInput, Prisma.PortfolioHistoryUncheckedUpdateManyWithoutCoinInput>
}

export type PortfolioHistoryCreateManyUserInput = {
  id?: string
  coinId: string
  date?: Date | string
  usdValue: number
}

export type PortfolioHistoryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
  coin?: Prisma.CoinUpdateOneRequiredWithoutPortfolioHistoryNestedInput
}

export type PortfolioHistoryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PortfolioHistoryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PortfolioHistoryCreateManyCoinInput = {
  id?: string
  userId: string
  date?: Date | string
  usdValue: number
}

export type PortfolioHistoryUpdateWithoutCoinInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutPortfolioHistoryNestedInput
}

export type PortfolioHistoryUncheckedUpdateWithoutCoinInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PortfolioHistoryUncheckedUpdateManyWithoutCoinInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usdValue?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type PortfolioHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  coinId?: boolean
  date?: boolean
  usdValue?: boolean
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["portfolioHistory"]>

export type PortfolioHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  coinId?: boolean
  date?: boolean
  usdValue?: boolean
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["portfolioHistory"]>

export type PortfolioHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  coinId?: boolean
  date?: boolean
  usdValue?: boolean
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["portfolioHistory"]>

export type PortfolioHistorySelectScalar = {
  id?: boolean
  userId?: boolean
  coinId?: boolean
  date?: boolean
  usdValue?: boolean
}

export type PortfolioHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "coinId" | "date" | "usdValue", ExtArgs["result"]["portfolioHistory"]>
export type PortfolioHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PortfolioHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PortfolioHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PortfolioHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PortfolioHistory"
  objects: {
    coin: Prisma.$CoinPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    coinId: string
    date: Date
    usdValue: number
  }, ExtArgs["result"]["portfolioHistory"]>
  composites: {}
}

export type PortfolioHistoryGetPayload<S extends boolean | null | undefined | PortfolioHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload, S>

export type PortfolioHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PortfolioHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PortfolioHistoryCountAggregateInputType | true
  }

export interface PortfolioHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PortfolioHistory'], meta: { name: 'PortfolioHistory' } }
  /**
   * Find zero or one PortfolioHistory that matches the filter.
   * @param {PortfolioHistoryFindUniqueArgs} args - Arguments to find a PortfolioHistory
   * @example
   * // Get one PortfolioHistory
   * const portfolioHistory = await prisma.portfolioHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PortfolioHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PortfolioHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PortfolioHistoryFindUniqueOrThrowArgs} args - Arguments to find a PortfolioHistory
   * @example
   * // Get one PortfolioHistory
   * const portfolioHistory = await prisma.portfolioHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PortfolioHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PortfolioHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PortfolioHistoryFindFirstArgs} args - Arguments to find a PortfolioHistory
   * @example
   * // Get one PortfolioHistory
   * const portfolioHistory = await prisma.portfolioHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PortfolioHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, PortfolioHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PortfolioHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PortfolioHistoryFindFirstOrThrowArgs} args - Arguments to find a PortfolioHistory
   * @example
   * // Get one PortfolioHistory
   * const portfolioHistory = await prisma.portfolioHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PortfolioHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PortfolioHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PortfolioHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PortfolioHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PortfolioHistories
   * const portfolioHistories = await prisma.portfolioHistory.findMany()
   * 
   * // Get first 10 PortfolioHistories
   * const portfolioHistories = await prisma.portfolioHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const portfolioHistoryWithIdOnly = await prisma.portfolioHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PortfolioHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, PortfolioHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PortfolioHistory.
   * @param {PortfolioHistoryCreateArgs} args - Arguments to create a PortfolioHistory.
   * @example
   * // Create one PortfolioHistory
   * const PortfolioHistory = await prisma.portfolioHistory.create({
   *   data: {
   *     // ... data to create a PortfolioHistory
   *   }
   * })
   * 
   */
  create<T extends PortfolioHistoryCreateArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PortfolioHistories.
   * @param {PortfolioHistoryCreateManyArgs} args - Arguments to create many PortfolioHistories.
   * @example
   * // Create many PortfolioHistories
   * const portfolioHistory = await prisma.portfolioHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PortfolioHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, PortfolioHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PortfolioHistories and returns the data saved in the database.
   * @param {PortfolioHistoryCreateManyAndReturnArgs} args - Arguments to create many PortfolioHistories.
   * @example
   * // Create many PortfolioHistories
   * const portfolioHistory = await prisma.portfolioHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PortfolioHistories and only return the `id`
   * const portfolioHistoryWithIdOnly = await prisma.portfolioHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PortfolioHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PortfolioHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PortfolioHistory.
   * @param {PortfolioHistoryDeleteArgs} args - Arguments to delete one PortfolioHistory.
   * @example
   * // Delete one PortfolioHistory
   * const PortfolioHistory = await prisma.portfolioHistory.delete({
   *   where: {
   *     // ... filter to delete one PortfolioHistory
   *   }
   * })
   * 
   */
  delete<T extends PortfolioHistoryDeleteArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PortfolioHistory.
   * @param {PortfolioHistoryUpdateArgs} args - Arguments to update one PortfolioHistory.
   * @example
   * // Update one PortfolioHistory
   * const portfolioHistory = await prisma.portfolioHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PortfolioHistoryUpdateArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PortfolioHistories.
   * @param {PortfolioHistoryDeleteManyArgs} args - Arguments to filter PortfolioHistories to delete.
   * @example
   * // Delete a few PortfolioHistories
   * const { count } = await prisma.portfolioHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PortfolioHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, PortfolioHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PortfolioHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PortfolioHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PortfolioHistories
   * const portfolioHistory = await prisma.portfolioHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PortfolioHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PortfolioHistories and returns the data updated in the database.
   * @param {PortfolioHistoryUpdateManyAndReturnArgs} args - Arguments to update many PortfolioHistories.
   * @example
   * // Update many PortfolioHistories
   * const portfolioHistory = await prisma.portfolioHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PortfolioHistories and only return the `id`
   * const portfolioHistoryWithIdOnly = await prisma.portfolioHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PortfolioHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PortfolioHistory.
   * @param {PortfolioHistoryUpsertArgs} args - Arguments to update or create a PortfolioHistory.
   * @example
   * // Update or create a PortfolioHistory
   * const portfolioHistory = await prisma.portfolioHistory.upsert({
   *   create: {
   *     // ... data to create a PortfolioHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PortfolioHistory we want to update
   *   }
   * })
   */
  upsert<T extends PortfolioHistoryUpsertArgs>(args: Prisma.SelectSubset<T, PortfolioHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__PortfolioHistoryClient<runtime.Types.Result.GetResult<Prisma.$PortfolioHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PortfolioHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PortfolioHistoryCountArgs} args - Arguments to filter PortfolioHistories to count.
   * @example
   * // Count the number of PortfolioHistories
   * const count = await prisma.portfolioHistory.count({
   *   where: {
   *     // ... the filter for the PortfolioHistories we want to count
   *   }
   * })
  **/
  count<T extends PortfolioHistoryCountArgs>(
    args?: Prisma.Subset<T, PortfolioHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PortfolioHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PortfolioHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PortfolioHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PortfolioHistoryAggregateArgs>(args: Prisma.Subset<T, PortfolioHistoryAggregateArgs>): Prisma.PrismaPromise<GetPortfolioHistoryAggregateType<T>>

  /**
   * Group by PortfolioHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PortfolioHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PortfolioHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PortfolioHistoryGroupByArgs['orderBy'] }
      : { orderBy?: PortfolioHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PortfolioHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPortfolioHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PortfolioHistory model
 */
readonly fields: PortfolioHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PortfolioHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PortfolioHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  coin<T extends Prisma.CoinDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CoinDefaultArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PortfolioHistory model
 */
export interface PortfolioHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"PortfolioHistory", 'String'>
  readonly userId: Prisma.FieldRef<"PortfolioHistory", 'String'>
  readonly coinId: Prisma.FieldRef<"PortfolioHistory", 'String'>
  readonly date: Prisma.FieldRef<"PortfolioHistory", 'DateTime'>
  readonly usdValue: Prisma.FieldRef<"PortfolioHistory", 'Float'>
}
    

// Custom InputTypes
/**
 * PortfolioHistory findUnique
 */
export type PortfolioHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * Filter, which PortfolioHistory to fetch.
   */
  where: Prisma.PortfolioHistoryWhereUniqueInput
}

/**
 * PortfolioHistory findUniqueOrThrow
 */
export type PortfolioHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * Filter, which PortfolioHistory to fetch.
   */
  where: Prisma.PortfolioHistoryWhereUniqueInput
}

/**
 * PortfolioHistory findFirst
 */
export type PortfolioHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * Filter, which PortfolioHistory to fetch.
   */
  where?: Prisma.PortfolioHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PortfolioHistories to fetch.
   */
  orderBy?: Prisma.PortfolioHistoryOrderByWithRelationInput | Prisma.PortfolioHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PortfolioHistories.
   */
  cursor?: Prisma.PortfolioHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PortfolioHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PortfolioHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PortfolioHistories.
   */
  distinct?: Prisma.PortfolioHistoryScalarFieldEnum | Prisma.PortfolioHistoryScalarFieldEnum[]
}

/**
 * PortfolioHistory findFirstOrThrow
 */
export type PortfolioHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * Filter, which PortfolioHistory to fetch.
   */
  where?: Prisma.PortfolioHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PortfolioHistories to fetch.
   */
  orderBy?: Prisma.PortfolioHistoryOrderByWithRelationInput | Prisma.PortfolioHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PortfolioHistories.
   */
  cursor?: Prisma.PortfolioHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PortfolioHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PortfolioHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PortfolioHistories.
   */
  distinct?: Prisma.PortfolioHistoryScalarFieldEnum | Prisma.PortfolioHistoryScalarFieldEnum[]
}

/**
 * PortfolioHistory findMany
 */
export type PortfolioHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * Filter, which PortfolioHistories to fetch.
   */
  where?: Prisma.PortfolioHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PortfolioHistories to fetch.
   */
  orderBy?: Prisma.PortfolioHistoryOrderByWithRelationInput | Prisma.PortfolioHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PortfolioHistories.
   */
  cursor?: Prisma.PortfolioHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PortfolioHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PortfolioHistories.
   */
  skip?: number
  distinct?: Prisma.PortfolioHistoryScalarFieldEnum | Prisma.PortfolioHistoryScalarFieldEnum[]
}

/**
 * PortfolioHistory create
 */
export type PortfolioHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a PortfolioHistory.
   */
  data: Prisma.XOR<Prisma.PortfolioHistoryCreateInput, Prisma.PortfolioHistoryUncheckedCreateInput>
}

/**
 * PortfolioHistory createMany
 */
export type PortfolioHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PortfolioHistories.
   */
  data: Prisma.PortfolioHistoryCreateManyInput | Prisma.PortfolioHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PortfolioHistory createManyAndReturn
 */
export type PortfolioHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many PortfolioHistories.
   */
  data: Prisma.PortfolioHistoryCreateManyInput | Prisma.PortfolioHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PortfolioHistory update
 */
export type PortfolioHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a PortfolioHistory.
   */
  data: Prisma.XOR<Prisma.PortfolioHistoryUpdateInput, Prisma.PortfolioHistoryUncheckedUpdateInput>
  /**
   * Choose, which PortfolioHistory to update.
   */
  where: Prisma.PortfolioHistoryWhereUniqueInput
}

/**
 * PortfolioHistory updateMany
 */
export type PortfolioHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PortfolioHistories.
   */
  data: Prisma.XOR<Prisma.PortfolioHistoryUpdateManyMutationInput, Prisma.PortfolioHistoryUncheckedUpdateManyInput>
  /**
   * Filter which PortfolioHistories to update
   */
  where?: Prisma.PortfolioHistoryWhereInput
  /**
   * Limit how many PortfolioHistories to update.
   */
  limit?: number
}

/**
 * PortfolioHistory updateManyAndReturn
 */
export type PortfolioHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * The data used to update PortfolioHistories.
   */
  data: Prisma.XOR<Prisma.PortfolioHistoryUpdateManyMutationInput, Prisma.PortfolioHistoryUncheckedUpdateManyInput>
  /**
   * Filter which PortfolioHistories to update
   */
  where?: Prisma.PortfolioHistoryWhereInput
  /**
   * Limit how many PortfolioHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PortfolioHistory upsert
 */
export type PortfolioHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the PortfolioHistory to update in case it exists.
   */
  where: Prisma.PortfolioHistoryWhereUniqueInput
  /**
   * In case the PortfolioHistory found by the `where` argument doesn't exist, create a new PortfolioHistory with this data.
   */
  create: Prisma.XOR<Prisma.PortfolioHistoryCreateInput, Prisma.PortfolioHistoryUncheckedCreateInput>
  /**
   * In case the PortfolioHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PortfolioHistoryUpdateInput, Prisma.PortfolioHistoryUncheckedUpdateInput>
}

/**
 * PortfolioHistory delete
 */
export type PortfolioHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
  /**
   * Filter which PortfolioHistory to delete.
   */
  where: Prisma.PortfolioHistoryWhereUniqueInput
}

/**
 * PortfolioHistory deleteMany
 */
export type PortfolioHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PortfolioHistories to delete
   */
  where?: Prisma.PortfolioHistoryWhereInput
  /**
   * Limit how many PortfolioHistories to delete.
   */
  limit?: number
}

/**
 * PortfolioHistory without action
 */
export type PortfolioHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PortfolioHistory
   */
  select?: Prisma.PortfolioHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PortfolioHistory
   */
  omit?: Prisma.PortfolioHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PortfolioHistoryInclude<ExtArgs> | null
}
