
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserCoin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserCoin
 * 
 */
export type UserCoinModel = runtime.Types.Result.DefaultSelection<Prisma.$UserCoinPayload>

export type AggregateUserCoin = {
  _count: UserCoinCountAggregateOutputType | null
  _min: UserCoinMinAggregateOutputType | null
  _max: UserCoinMaxAggregateOutputType | null
}

export type UserCoinMinAggregateOutputType = {
  userId: string | null
  coinId: string | null
  isOptimistic: boolean | null
}

export type UserCoinMaxAggregateOutputType = {
  userId: string | null
  coinId: string | null
  isOptimistic: boolean | null
}

export type UserCoinCountAggregateOutputType = {
  userId: number
  coinId: number
  isOptimistic: number
  _all: number
}


export type UserCoinMinAggregateInputType = {
  userId?: true
  coinId?: true
  isOptimistic?: true
}

export type UserCoinMaxAggregateInputType = {
  userId?: true
  coinId?: true
  isOptimistic?: true
}

export type UserCoinCountAggregateInputType = {
  userId?: true
  coinId?: true
  isOptimistic?: true
  _all?: true
}

export type UserCoinAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserCoin to aggregate.
   */
  where?: Prisma.UserCoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCoins to fetch.
   */
  orderBy?: Prisma.UserCoinOrderByWithRelationInput | Prisma.UserCoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserCoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCoins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCoins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserCoins
  **/
  _count?: true | UserCoinCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserCoinMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserCoinMaxAggregateInputType
}

export type GetUserCoinAggregateType<T extends UserCoinAggregateArgs> = {
      [P in keyof T & keyof AggregateUserCoin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserCoin[P]>
    : Prisma.GetScalarType<T[P], AggregateUserCoin[P]>
}




export type UserCoinGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserCoinWhereInput
  orderBy?: Prisma.UserCoinOrderByWithAggregationInput | Prisma.UserCoinOrderByWithAggregationInput[]
  by: Prisma.UserCoinScalarFieldEnum[] | Prisma.UserCoinScalarFieldEnum
  having?: Prisma.UserCoinScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCoinCountAggregateInputType | true
  _min?: UserCoinMinAggregateInputType
  _max?: UserCoinMaxAggregateInputType
}

export type UserCoinGroupByOutputType = {
  userId: string
  coinId: string
  isOptimistic: boolean | null
  _count: UserCoinCountAggregateOutputType | null
  _min: UserCoinMinAggregateOutputType | null
  _max: UserCoinMaxAggregateOutputType | null
}

type GetUserCoinGroupByPayload<T extends UserCoinGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserCoinGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserCoinGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserCoinGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserCoinGroupByOutputType[P]>
      }
    >
  >



export type UserCoinWhereInput = {
  AND?: Prisma.UserCoinWhereInput | Prisma.UserCoinWhereInput[]
  OR?: Prisma.UserCoinWhereInput[]
  NOT?: Prisma.UserCoinWhereInput | Prisma.UserCoinWhereInput[]
  userId?: Prisma.StringFilter<"UserCoin"> | string
  coinId?: Prisma.StringFilter<"UserCoin"> | string
  isOptimistic?: Prisma.BoolNullableFilter<"UserCoin"> | boolean | null
  coin?: Prisma.XOR<Prisma.CoinScalarRelationFilter, Prisma.CoinWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserCoinOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  isOptimistic?: Prisma.SortOrderInput | Prisma.SortOrder
  coin?: Prisma.CoinOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserCoinWhereUniqueInput = Prisma.AtLeast<{
  userId_coinId?: Prisma.UserCoinUserIdCoinIdCompoundUniqueInput
  AND?: Prisma.UserCoinWhereInput | Prisma.UserCoinWhereInput[]
  OR?: Prisma.UserCoinWhereInput[]
  NOT?: Prisma.UserCoinWhereInput | Prisma.UserCoinWhereInput[]
  userId?: Prisma.StringFilter<"UserCoin"> | string
  coinId?: Prisma.StringFilter<"UserCoin"> | string
  isOptimistic?: Prisma.BoolNullableFilter<"UserCoin"> | boolean | null
  coin?: Prisma.XOR<Prisma.CoinScalarRelationFilter, Prisma.CoinWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "userId_coinId">

export type UserCoinOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  isOptimistic?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserCoinCountOrderByAggregateInput
  _max?: Prisma.UserCoinMaxOrderByAggregateInput
  _min?: Prisma.UserCoinMinOrderByAggregateInput
}

export type UserCoinScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserCoinScalarWhereWithAggregatesInput | Prisma.UserCoinScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserCoinScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserCoinScalarWhereWithAggregatesInput | Prisma.UserCoinScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"UserCoin"> | string
  coinId?: Prisma.StringWithAggregatesFilter<"UserCoin"> | string
  isOptimistic?: Prisma.BoolNullableWithAggregatesFilter<"UserCoin"> | boolean | null
}

export type UserCoinCreateInput = {
  isOptimistic?: boolean | null
  coin: Prisma.CoinCreateNestedOneWithoutUserCoinsInput
  user: Prisma.UserCreateNestedOneWithoutCoinsInput
}

export type UserCoinUncheckedCreateInput = {
  userId: string
  coinId: string
  isOptimistic?: boolean | null
}

export type UserCoinUpdateInput = {
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  coin?: Prisma.CoinUpdateOneRequiredWithoutUserCoinsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutCoinsNestedInput
}

export type UserCoinUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UserCoinCreateManyInput = {
  userId: string
  coinId: string
  isOptimistic?: boolean | null
}

export type UserCoinUpdateManyMutationInput = {
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UserCoinUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UserCoinListRelationFilter = {
  every?: Prisma.UserCoinWhereInput
  some?: Prisma.UserCoinWhereInput
  none?: Prisma.UserCoinWhereInput
}

export type UserCoinOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserCoinUserIdCoinIdCompoundUniqueInput = {
  userId: string
  coinId: string
}

export type UserCoinCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  isOptimistic?: Prisma.SortOrder
}

export type UserCoinMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  isOptimistic?: Prisma.SortOrder
}

export type UserCoinMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  coinId?: Prisma.SortOrder
  isOptimistic?: Prisma.SortOrder
}

export type UserCoinCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutUserInput, Prisma.UserCoinUncheckedCreateWithoutUserInput> | Prisma.UserCoinCreateWithoutUserInput[] | Prisma.UserCoinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutUserInput | Prisma.UserCoinCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserCoinCreateManyUserInputEnvelope
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
}

export type UserCoinUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutUserInput, Prisma.UserCoinUncheckedCreateWithoutUserInput> | Prisma.UserCoinCreateWithoutUserInput[] | Prisma.UserCoinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutUserInput | Prisma.UserCoinCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserCoinCreateManyUserInputEnvelope
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
}

export type UserCoinUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutUserInput, Prisma.UserCoinUncheckedCreateWithoutUserInput> | Prisma.UserCoinCreateWithoutUserInput[] | Prisma.UserCoinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutUserInput | Prisma.UserCoinCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserCoinUpsertWithWhereUniqueWithoutUserInput | Prisma.UserCoinUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserCoinCreateManyUserInputEnvelope
  set?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  disconnect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  delete?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  update?: Prisma.UserCoinUpdateWithWhereUniqueWithoutUserInput | Prisma.UserCoinUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserCoinUpdateManyWithWhereWithoutUserInput | Prisma.UserCoinUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserCoinScalarWhereInput | Prisma.UserCoinScalarWhereInput[]
}

export type UserCoinUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutUserInput, Prisma.UserCoinUncheckedCreateWithoutUserInput> | Prisma.UserCoinCreateWithoutUserInput[] | Prisma.UserCoinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutUserInput | Prisma.UserCoinCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserCoinUpsertWithWhereUniqueWithoutUserInput | Prisma.UserCoinUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserCoinCreateManyUserInputEnvelope
  set?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  disconnect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  delete?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  update?: Prisma.UserCoinUpdateWithWhereUniqueWithoutUserInput | Prisma.UserCoinUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserCoinUpdateManyWithWhereWithoutUserInput | Prisma.UserCoinUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserCoinScalarWhereInput | Prisma.UserCoinScalarWhereInput[]
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type UserCoinCreateNestedManyWithoutCoinInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutCoinInput, Prisma.UserCoinUncheckedCreateWithoutCoinInput> | Prisma.UserCoinCreateWithoutCoinInput[] | Prisma.UserCoinUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutCoinInput | Prisma.UserCoinCreateOrConnectWithoutCoinInput[]
  createMany?: Prisma.UserCoinCreateManyCoinInputEnvelope
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
}

export type UserCoinUncheckedCreateNestedManyWithoutCoinInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutCoinInput, Prisma.UserCoinUncheckedCreateWithoutCoinInput> | Prisma.UserCoinCreateWithoutCoinInput[] | Prisma.UserCoinUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutCoinInput | Prisma.UserCoinCreateOrConnectWithoutCoinInput[]
  createMany?: Prisma.UserCoinCreateManyCoinInputEnvelope
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
}

export type UserCoinUpdateManyWithoutCoinNestedInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutCoinInput, Prisma.UserCoinUncheckedCreateWithoutCoinInput> | Prisma.UserCoinCreateWithoutCoinInput[] | Prisma.UserCoinUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutCoinInput | Prisma.UserCoinCreateOrConnectWithoutCoinInput[]
  upsert?: Prisma.UserCoinUpsertWithWhereUniqueWithoutCoinInput | Prisma.UserCoinUpsertWithWhereUniqueWithoutCoinInput[]
  createMany?: Prisma.UserCoinCreateManyCoinInputEnvelope
  set?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  disconnect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  delete?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  update?: Prisma.UserCoinUpdateWithWhereUniqueWithoutCoinInput | Prisma.UserCoinUpdateWithWhereUniqueWithoutCoinInput[]
  updateMany?: Prisma.UserCoinUpdateManyWithWhereWithoutCoinInput | Prisma.UserCoinUpdateManyWithWhereWithoutCoinInput[]
  deleteMany?: Prisma.UserCoinScalarWhereInput | Prisma.UserCoinScalarWhereInput[]
}

export type UserCoinUncheckedUpdateManyWithoutCoinNestedInput = {
  create?: Prisma.XOR<Prisma.UserCoinCreateWithoutCoinInput, Prisma.UserCoinUncheckedCreateWithoutCoinInput> | Prisma.UserCoinCreateWithoutCoinInput[] | Prisma.UserCoinUncheckedCreateWithoutCoinInput[]
  connectOrCreate?: Prisma.UserCoinCreateOrConnectWithoutCoinInput | Prisma.UserCoinCreateOrConnectWithoutCoinInput[]
  upsert?: Prisma.UserCoinUpsertWithWhereUniqueWithoutCoinInput | Prisma.UserCoinUpsertWithWhereUniqueWithoutCoinInput[]
  createMany?: Prisma.UserCoinCreateManyCoinInputEnvelope
  set?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  disconnect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  delete?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  connect?: Prisma.UserCoinWhereUniqueInput | Prisma.UserCoinWhereUniqueInput[]
  update?: Prisma.UserCoinUpdateWithWhereUniqueWithoutCoinInput | Prisma.UserCoinUpdateWithWhereUniqueWithoutCoinInput[]
  updateMany?: Prisma.UserCoinUpdateManyWithWhereWithoutCoinInput | Prisma.UserCoinUpdateManyWithWhereWithoutCoinInput[]
  deleteMany?: Prisma.UserCoinScalarWhereInput | Prisma.UserCoinScalarWhereInput[]
}

export type UserCoinCreateWithoutUserInput = {
  isOptimistic?: boolean | null
  coin: Prisma.CoinCreateNestedOneWithoutUserCoinsInput
}

export type UserCoinUncheckedCreateWithoutUserInput = {
  coinId: string
  isOptimistic?: boolean | null
}

export type UserCoinCreateOrConnectWithoutUserInput = {
  where: Prisma.UserCoinWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCoinCreateWithoutUserInput, Prisma.UserCoinUncheckedCreateWithoutUserInput>
}

export type UserCoinCreateManyUserInputEnvelope = {
  data: Prisma.UserCoinCreateManyUserInput | Prisma.UserCoinCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserCoinUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserCoinWhereUniqueInput
  update: Prisma.XOR<Prisma.UserCoinUpdateWithoutUserInput, Prisma.UserCoinUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserCoinCreateWithoutUserInput, Prisma.UserCoinUncheckedCreateWithoutUserInput>
}

export type UserCoinUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserCoinWhereUniqueInput
  data: Prisma.XOR<Prisma.UserCoinUpdateWithoutUserInput, Prisma.UserCoinUncheckedUpdateWithoutUserInput>
}

export type UserCoinUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserCoinScalarWhereInput
  data: Prisma.XOR<Prisma.UserCoinUpdateManyMutationInput, Prisma.UserCoinUncheckedUpdateManyWithoutUserInput>
}

export type UserCoinScalarWhereInput = {
  AND?: Prisma.UserCoinScalarWhereInput | Prisma.UserCoinScalarWhereInput[]
  OR?: Prisma.UserCoinScalarWhereInput[]
  NOT?: Prisma.UserCoinScalarWhereInput | Prisma.UserCoinScalarWhereInput[]
  userId?: Prisma.StringFilter<"UserCoin"> | string
  coinId?: Prisma.StringFilter<"UserCoin"> | string
  isOptimistic?: Prisma.BoolNullableFilter<"UserCoin"> | boolean | null
}

export type UserCoinCreateWithoutCoinInput = {
  isOptimistic?: boolean | null
  user: Prisma.UserCreateNestedOneWithoutCoinsInput
}

export type UserCoinUncheckedCreateWithoutCoinInput = {
  userId: string
  isOptimistic?: boolean | null
}

export type UserCoinCreateOrConnectWithoutCoinInput = {
  where: Prisma.UserCoinWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCoinCreateWithoutCoinInput, Prisma.UserCoinUncheckedCreateWithoutCoinInput>
}

export type UserCoinCreateManyCoinInputEnvelope = {
  data: Prisma.UserCoinCreateManyCoinInput | Prisma.UserCoinCreateManyCoinInput[]
  skipDuplicates?: boolean
}

export type UserCoinUpsertWithWhereUniqueWithoutCoinInput = {
  where: Prisma.UserCoinWhereUniqueInput
  update: Prisma.XOR<Prisma.UserCoinUpdateWithoutCoinInput, Prisma.UserCoinUncheckedUpdateWithoutCoinInput>
  create: Prisma.XOR<Prisma.UserCoinCreateWithoutCoinInput, Prisma.UserCoinUncheckedCreateWithoutCoinInput>
}

export type UserCoinUpdateWithWhereUniqueWithoutCoinInput = {
  where: Prisma.UserCoinWhereUniqueInput
  data: Prisma.XOR<Prisma.UserCoinUpdateWithoutCoinInput, Prisma.UserCoinUncheckedUpdateWithoutCoinInput>
}

export type UserCoinUpdateManyWithWhereWithoutCoinInput = {
  where: Prisma.UserCoinScalarWhereInput
  data: Prisma.XOR<Prisma.UserCoinUpdateManyMutationInput, Prisma.UserCoinUncheckedUpdateManyWithoutCoinInput>
}

export type UserCoinCreateManyUserInput = {
  coinId: string
  isOptimistic?: boolean | null
}

export type UserCoinUpdateWithoutUserInput = {
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  coin?: Prisma.CoinUpdateOneRequiredWithoutUserCoinsNestedInput
}

export type UserCoinUncheckedUpdateWithoutUserInput = {
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UserCoinUncheckedUpdateManyWithoutUserInput = {
  coinId?: Prisma.StringFieldUpdateOperationsInput | string
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UserCoinCreateManyCoinInput = {
  userId: string
  isOptimistic?: boolean | null
}

export type UserCoinUpdateWithoutCoinInput = {
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  user?: Prisma.UserUpdateOneRequiredWithoutCoinsNestedInput
}

export type UserCoinUncheckedUpdateWithoutCoinInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UserCoinUncheckedUpdateManyWithoutCoinInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isOptimistic?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}



export type UserCoinSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  coinId?: boolean
  isOptimistic?: boolean
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userCoin"]>

export type UserCoinSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  coinId?: boolean
  isOptimistic?: boolean
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userCoin"]>

export type UserCoinSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  coinId?: boolean
  isOptimistic?: boolean
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userCoin"]>

export type UserCoinSelectScalar = {
  userId?: boolean
  coinId?: boolean
  isOptimistic?: boolean
}

export type UserCoinOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "coinId" | "isOptimistic", ExtArgs["result"]["userCoin"]>
export type UserCoinInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserCoinIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserCoinIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coin?: boolean | Prisma.CoinDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserCoinPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserCoin"
  objects: {
    coin: Prisma.$CoinPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    coinId: string
    isOptimistic: boolean | null
  }, ExtArgs["result"]["userCoin"]>
  composites: {}
}

export type UserCoinGetPayload<S extends boolean | null | undefined | UserCoinDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserCoinPayload, S>

export type UserCoinCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserCoinFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCoinCountAggregateInputType | true
  }

export interface UserCoinDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserCoin'], meta: { name: 'UserCoin' } }
  /**
   * Find zero or one UserCoin that matches the filter.
   * @param {UserCoinFindUniqueArgs} args - Arguments to find a UserCoin
   * @example
   * // Get one UserCoin
   * const userCoin = await prisma.userCoin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserCoinFindUniqueArgs>(args: Prisma.SelectSubset<T, UserCoinFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserCoin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserCoinFindUniqueOrThrowArgs} args - Arguments to find a UserCoin
   * @example
   * // Get one UserCoin
   * const userCoin = await prisma.userCoin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserCoinFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserCoinFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserCoin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCoinFindFirstArgs} args - Arguments to find a UserCoin
   * @example
   * // Get one UserCoin
   * const userCoin = await prisma.userCoin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserCoinFindFirstArgs>(args?: Prisma.SelectSubset<T, UserCoinFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserCoin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCoinFindFirstOrThrowArgs} args - Arguments to find a UserCoin
   * @example
   * // Get one UserCoin
   * const userCoin = await prisma.userCoin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserCoinFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserCoinFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserCoins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCoinFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserCoins
   * const userCoins = await prisma.userCoin.findMany()
   * 
   * // Get first 10 UserCoins
   * const userCoins = await prisma.userCoin.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const userCoinWithUserIdOnly = await prisma.userCoin.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends UserCoinFindManyArgs>(args?: Prisma.SelectSubset<T, UserCoinFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserCoin.
   * @param {UserCoinCreateArgs} args - Arguments to create a UserCoin.
   * @example
   * // Create one UserCoin
   * const UserCoin = await prisma.userCoin.create({
   *   data: {
   *     // ... data to create a UserCoin
   *   }
   * })
   * 
   */
  create<T extends UserCoinCreateArgs>(args: Prisma.SelectSubset<T, UserCoinCreateArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserCoins.
   * @param {UserCoinCreateManyArgs} args - Arguments to create many UserCoins.
   * @example
   * // Create many UserCoins
   * const userCoin = await prisma.userCoin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCoinCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCoinCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserCoins and returns the data saved in the database.
   * @param {UserCoinCreateManyAndReturnArgs} args - Arguments to create many UserCoins.
   * @example
   * // Create many UserCoins
   * const userCoin = await prisma.userCoin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserCoins and only return the `userId`
   * const userCoinWithUserIdOnly = await prisma.userCoin.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCoinCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCoinCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserCoin.
   * @param {UserCoinDeleteArgs} args - Arguments to delete one UserCoin.
   * @example
   * // Delete one UserCoin
   * const UserCoin = await prisma.userCoin.delete({
   *   where: {
   *     // ... filter to delete one UserCoin
   *   }
   * })
   * 
   */
  delete<T extends UserCoinDeleteArgs>(args: Prisma.SelectSubset<T, UserCoinDeleteArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserCoin.
   * @param {UserCoinUpdateArgs} args - Arguments to update one UserCoin.
   * @example
   * // Update one UserCoin
   * const userCoin = await prisma.userCoin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserCoinUpdateArgs>(args: Prisma.SelectSubset<T, UserCoinUpdateArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserCoins.
   * @param {UserCoinDeleteManyArgs} args - Arguments to filter UserCoins to delete.
   * @example
   * // Delete a few UserCoins
   * const { count } = await prisma.userCoin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserCoinDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserCoinDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserCoins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCoinUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserCoins
   * const userCoin = await prisma.userCoin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserCoinUpdateManyArgs>(args: Prisma.SelectSubset<T, UserCoinUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserCoins and returns the data updated in the database.
   * @param {UserCoinUpdateManyAndReturnArgs} args - Arguments to update many UserCoins.
   * @example
   * // Update many UserCoins
   * const userCoin = await prisma.userCoin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserCoins and only return the `userId`
   * const userCoinWithUserIdOnly = await prisma.userCoin.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserCoinUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserCoinUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserCoin.
   * @param {UserCoinUpsertArgs} args - Arguments to update or create a UserCoin.
   * @example
   * // Update or create a UserCoin
   * const userCoin = await prisma.userCoin.upsert({
   *   create: {
   *     // ... data to create a UserCoin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserCoin we want to update
   *   }
   * })
   */
  upsert<T extends UserCoinUpsertArgs>(args: Prisma.SelectSubset<T, UserCoinUpsertArgs<ExtArgs>>): Prisma.Prisma__UserCoinClient<runtime.Types.Result.GetResult<Prisma.$UserCoinPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserCoins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCoinCountArgs} args - Arguments to filter UserCoins to count.
   * @example
   * // Count the number of UserCoins
   * const count = await prisma.userCoin.count({
   *   where: {
   *     // ... the filter for the UserCoins we want to count
   *   }
   * })
  **/
  count<T extends UserCoinCountArgs>(
    args?: Prisma.Subset<T, UserCoinCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCoinCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserCoin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCoinAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserCoinAggregateArgs>(args: Prisma.Subset<T, UserCoinAggregateArgs>): Prisma.PrismaPromise<GetUserCoinAggregateType<T>>

  /**
   * Group by UserCoin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCoinGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserCoinGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserCoinGroupByArgs['orderBy'] }
      : { orderBy?: UserCoinGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserCoinGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserCoinGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserCoin model
 */
readonly fields: UserCoinFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserCoin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserCoinClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  coin<T extends Prisma.CoinDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CoinDefaultArgs<ExtArgs>>): Prisma.Prisma__CoinClient<runtime.Types.Result.GetResult<Prisma.$CoinPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserCoin model
 */
export interface UserCoinFieldRefs {
  readonly userId: Prisma.FieldRef<"UserCoin", 'String'>
  readonly coinId: Prisma.FieldRef<"UserCoin", 'String'>
  readonly isOptimistic: Prisma.FieldRef<"UserCoin", 'Boolean'>
}
    

// Custom InputTypes
/**
 * UserCoin findUnique
 */
export type UserCoinFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * Filter, which UserCoin to fetch.
   */
  where: Prisma.UserCoinWhereUniqueInput
}

/**
 * UserCoin findUniqueOrThrow
 */
export type UserCoinFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * Filter, which UserCoin to fetch.
   */
  where: Prisma.UserCoinWhereUniqueInput
}

/**
 * UserCoin findFirst
 */
export type UserCoinFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * Filter, which UserCoin to fetch.
   */
  where?: Prisma.UserCoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCoins to fetch.
   */
  orderBy?: Prisma.UserCoinOrderByWithRelationInput | Prisma.UserCoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserCoins.
   */
  cursor?: Prisma.UserCoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCoins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCoins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserCoins.
   */
  distinct?: Prisma.UserCoinScalarFieldEnum | Prisma.UserCoinScalarFieldEnum[]
}

/**
 * UserCoin findFirstOrThrow
 */
export type UserCoinFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * Filter, which UserCoin to fetch.
   */
  where?: Prisma.UserCoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCoins to fetch.
   */
  orderBy?: Prisma.UserCoinOrderByWithRelationInput | Prisma.UserCoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserCoins.
   */
  cursor?: Prisma.UserCoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCoins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCoins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserCoins.
   */
  distinct?: Prisma.UserCoinScalarFieldEnum | Prisma.UserCoinScalarFieldEnum[]
}

/**
 * UserCoin findMany
 */
export type UserCoinFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * Filter, which UserCoins to fetch.
   */
  where?: Prisma.UserCoinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserCoins to fetch.
   */
  orderBy?: Prisma.UserCoinOrderByWithRelationInput | Prisma.UserCoinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserCoins.
   */
  cursor?: Prisma.UserCoinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserCoins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserCoins.
   */
  skip?: number
  distinct?: Prisma.UserCoinScalarFieldEnum | Prisma.UserCoinScalarFieldEnum[]
}

/**
 * UserCoin create
 */
export type UserCoinCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * The data needed to create a UserCoin.
   */
  data: Prisma.XOR<Prisma.UserCoinCreateInput, Prisma.UserCoinUncheckedCreateInput>
}

/**
 * UserCoin createMany
 */
export type UserCoinCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserCoins.
   */
  data: Prisma.UserCoinCreateManyInput | Prisma.UserCoinCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserCoin createManyAndReturn
 */
export type UserCoinCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * The data used to create many UserCoins.
   */
  data: Prisma.UserCoinCreateManyInput | Prisma.UserCoinCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserCoin update
 */
export type UserCoinUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * The data needed to update a UserCoin.
   */
  data: Prisma.XOR<Prisma.UserCoinUpdateInput, Prisma.UserCoinUncheckedUpdateInput>
  /**
   * Choose, which UserCoin to update.
   */
  where: Prisma.UserCoinWhereUniqueInput
}

/**
 * UserCoin updateMany
 */
export type UserCoinUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserCoins.
   */
  data: Prisma.XOR<Prisma.UserCoinUpdateManyMutationInput, Prisma.UserCoinUncheckedUpdateManyInput>
  /**
   * Filter which UserCoins to update
   */
  where?: Prisma.UserCoinWhereInput
  /**
   * Limit how many UserCoins to update.
   */
  limit?: number
}

/**
 * UserCoin updateManyAndReturn
 */
export type UserCoinUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * The data used to update UserCoins.
   */
  data: Prisma.XOR<Prisma.UserCoinUpdateManyMutationInput, Prisma.UserCoinUncheckedUpdateManyInput>
  /**
   * Filter which UserCoins to update
   */
  where?: Prisma.UserCoinWhereInput
  /**
   * Limit how many UserCoins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserCoin upsert
 */
export type UserCoinUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * The filter to search for the UserCoin to update in case it exists.
   */
  where: Prisma.UserCoinWhereUniqueInput
  /**
   * In case the UserCoin found by the `where` argument doesn't exist, create a new UserCoin with this data.
   */
  create: Prisma.XOR<Prisma.UserCoinCreateInput, Prisma.UserCoinUncheckedCreateInput>
  /**
   * In case the UserCoin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserCoinUpdateInput, Prisma.UserCoinUncheckedUpdateInput>
}

/**
 * UserCoin delete
 */
export type UserCoinDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
  /**
   * Filter which UserCoin to delete.
   */
  where: Prisma.UserCoinWhereUniqueInput
}

/**
 * UserCoin deleteMany
 */
export type UserCoinDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserCoins to delete
   */
  where?: Prisma.UserCoinWhereInput
  /**
   * Limit how many UserCoins to delete.
   */
  limit?: number
}

/**
 * UserCoin without action
 */
export type UserCoinDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCoin
   */
  select?: Prisma.UserCoinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserCoin
   */
  omit?: Prisma.UserCoinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserCoinInclude<ExtArgs> | null
}
